/**
 * sync-agent-gate.ts
 *
 * Keeps apps/agent/main_agent/services/validation/tsc_validator/agent_sdk_gate.d.ts
 * synchronized with packages/exepad-sdk/src/index.ts.
 *
 * The gate file is the declaration file the agent's tsc Stage-1.5 validator
 * resolves `@exepad/sdk` against (it does not link the actual SDK package
 * because that would pull in ~30 third-party trees). When the SDK barrel
 * adds an export but the gate is not regenerated, the LLM's `import { X }
 * from '@exepad/sdk'` trips `Module '"@exepad/sdk"' has no exported member`
 * — silently dead-on-arrival until someone notices.
 *
 * Runs as a postbuild step so every `pnpm build:sdk` propagates new exports
 * automatically. `--check` mode is for CI: exits non-zero if the gate would
 * change, so a PR that adds an SDK export without rebuilding fails its
 * status checks.
 *
 * Usage:
 *   pnpm --filter @exepad/sdk sync:agent-gate          # regenerate in-place
 *   pnpm --filter @exepad/sdk check:agent-gate         # exit 1 if drifted
 */

import * as ts from 'typescript';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename_local = fileURLToPath(import.meta.url);
const __dirname_local = path.dirname(__filename_local);
const REPO_ROOT = path.resolve(__dirname_local, '..', '..', '..');
const SDK_INDEX = path.join(REPO_ROOT, 'packages', 'exepad-sdk', 'src', 'index.ts');
const GATE_FILE = path.join(
  REPO_ROOT,
  'apps',
  'agent',
  'main_agent',
  'services',
  'validation',
  'tsc_validator',
  'agent_sdk_gate.d.ts',
);

const BEGIN_MARKER = '  // <<<AGENT_SDK_GATE_AUTOGEN_BEGIN>>>';
const END_MARKER = '  // <<<AGENT_SDK_GATE_AUTOGEN_END>>>';
const LEGACY_HEADER = '  // ── Auto-generated stubs for SDK barrel exports';

interface SdkExport {
  name: string;
  isType: boolean;
}

function extractSdkExports(): SdkExport[] {
  const content = fs.readFileSync(SDK_INDEX, 'utf-8');
  const sourceFile = ts.createSourceFile(SDK_INDEX, content, ts.ScriptTarget.Latest, true);
  const exports: SdkExport[] = [];

  for (const stmt of sourceFile.statements) {
    if (!ts.isExportDeclaration(stmt) || !stmt.exportClause) continue;
    if (!ts.isNamedExports(stmt.exportClause)) continue;
    const blockIsTypeOnly = stmt.isTypeOnly;
    for (const el of stmt.exportClause.elements) {
      const isType = blockIsTypeOnly || el.isTypeOnly;
      // The exported name is `name` (or the alias if `as` is used).
      exports.push({ name: el.name.text, isType });
    }
  }

  return exports;
}

const DECLARED_NAME_RE =
  /^\s*(?:declare\s+)?(?:const|function|interface|type)\s+([A-Za-z_$][A-Za-z0-9_$]*)/;

function collectDeclaredNames(text: string): Set<string> {
  const names = new Set<string>();
  for (const line of text.split('\n')) {
    const m = line.match(DECLARED_NAME_RE);
    if (m) names.add(m[1]);
  }
  return names;
}

function getHandWrittenSlice(gate: string): string {
  const beginIdx = gate.indexOf(BEGIN_MARKER);
  if (beginIdx !== -1) return gate.slice(0, beginIdx);
  const legacyIdx = gate.indexOf(LEGACY_HEADER);
  if (legacyIdx !== -1) return gate.slice(0, legacyIdx);
  return gate;
}

function buildAutogenBlock(exports: SdkExport[], handWritten: Set<string>): string {
  const valueStubs = new Set<string>();
  const typeStubs = new Set<string>();
  for (const exp of exports) {
    if (handWritten.has(exp.name)) continue;
    if (exp.isType) typeStubs.add(exp.name);
    else valueStubs.add(exp.name);
  }

  const lines: string[] = [
    BEGIN_MARKER,
    '  // Auto-generated by packages/exepad-sdk/scripts/sync-agent-gate.ts',
    '  // — DO NOT EDIT BY HAND. Edit packages/exepad-sdk/src/index.ts and',
    '  // rerun `pnpm --filter @exepad/sdk sync:agent-gate` (or `pnpm build:sdk`).',
    "  // All declared as `any`; the gate validates identifier names, not shapes.",
  ];
  for (const name of [...valueStubs].sort()) {
    lines.push(`  const ${name}: any;`);
  }
  if (typeStubs.size > 0) {
    lines.push('');
    lines.push('  // Type re-exports.');
    for (const name of [...typeStubs].sort()) {
      lines.push(`  type ${name} = any;`);
    }
  }
  lines.push(END_MARKER);
  return lines.join('\n');
}

function rewriteGate(gate: string, autogenBlock: string): string {
  const beginIdx = gate.indexOf(BEGIN_MARKER);
  const endIdx = gate.indexOf(END_MARKER);
  if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
    const before = gate.slice(0, beginIdx);
    const after = gate.slice(endIdx + END_MARKER.length);
    return before + autogenBlock + after;
  }

  // Legacy migration path — splice from the legacy header to just before
  // the module's closing `}`. Only runs once; subsequent calls take the
  // marker-based path above.
  const legacyIdx = gate.indexOf(LEGACY_HEADER);
  if (legacyIdx === -1) {
    throw new Error(
      'Could not locate autogen markers or legacy header in gate file. ' +
        'Aborting to avoid corrupting hand-curated content.',
    );
  }
  const trailing = gate.slice(legacyIdx);
  const closingMatch = trailing.match(/\n\}\s*$/m);
  if (!closingMatch || closingMatch.index === undefined) {
    throw new Error('Could not locate module closing brace after legacy autogen block.');
  }
  // closingMatch.index points at the `\n` preceding the closing `}`. Keep
  // exactly one blank line of separation between the END marker and `}`.
  const closingAbsIdx = legacyIdx + closingMatch.index + 1; // skip leading \n
  return gate.slice(0, legacyIdx) + autogenBlock + '\n\n' + gate.slice(closingAbsIdx);
}

function main(): void {
  const checkMode = process.argv.includes('--check');

  const exports = extractSdkExports();
  const gate = fs.readFileSync(GATE_FILE, 'utf-8');
  const handWritten = collectDeclaredNames(getHandWrittenSlice(gate));
  const autogenBlock = buildAutogenBlock(exports, handWritten);
  const updated = rewriteGate(gate, autogenBlock);

  if (updated === gate) {
    console.log(
      `agent_sdk_gate.d.ts already in sync (${exports.length} SDK exports scanned).`,
    );
    return;
  }

  if (checkMode) {
    console.error(
      'agent_sdk_gate.d.ts is OUT OF SYNC with packages/exepad-sdk/src/index.ts.',
    );
    console.error('Fix: pnpm --filter @exepad/sdk sync:agent-gate');
    process.exit(1);
  }

  fs.writeFileSync(GATE_FILE, updated, 'utf-8');
  const valueCount = (autogenBlock.match(/^\s*const\s+/gm) || []).length;
  const typeCount = (autogenBlock.match(/^\s*type\s+/gm) || []).length;
  console.log(
    `Updated agent_sdk_gate.d.ts — ${valueCount} value stubs, ${typeCount} type stubs ` +
      `(${exports.length} SDK exports scanned, ${handWritten.size} hand-curated names skipped).`,
  );
}

main();
