"""
BackendModelBuilder agent -- generates backend model config (mode + models[]).

Focused on model generation only. Handler metadata is derived mechanically
from BackendPlan.handlers in the workflow. Handler code is generated by
BackendHandlerBuilder.

Output: backend.json artifact containing mode and models[] fields.
"""

from typing import Literal, Optional

from google.adk.agents.readonly_context import ReadonlyContext
from google.adk.tools.skill_toolset import SkillToolset
from pydantic import BaseModel, Field, model_validator
from config import AgentName

from main_agent.agents.utils.skills import load_backend_skills

from ..builder_factory import create_json_config_builder
from .backend_artifact_tools import (
    backend_model_save_guardrail,
    sanitize_backend_model_save_response,
    validate_and_save_backend_artifact_tool,
)
from ...models.plan_models import ModelPlan

_BACKEND_SKILL_TOOLSET = SkillToolset(skills=load_backend_skills())


class BackendModelBuilderInput(BaseModel):
    """Input for the BackendModelBuilder agent.

    Receives only model-relevant fields, not the full BackendPlan.
    The orchestrator decomposes the plan and delivers focused slices.
    """

    build_mode: Literal["create", "edit"] = Field(
        description="Whether this is a new app creation or editing existing models.",
    )

    # -- Shared --
    model_plans: Optional[list[ModelPlan]] = Field(
        default=None,
        description="Model definitions. In create mode: from the creator plan. In edit mode: current deployed models.",
    )

    # -- Edit mode --
    editor_prompt: Optional[str] = Field(
        default=None,
        description="Free-text description of the model modification (edit mode only).",
    )

    @model_validator(mode="after")
    def check_mode_fields(self):
        if self.build_mode == "edit" and (self.model_plans is None or self.editor_prompt is None):
            raise ValueError("model_plans and editor_prompt required in edit mode")
        return self


def backend_model_builder_instruction_provider(context: ReadonlyContext) -> str:
    """Instruction provider for BackendModelBuilder.

    Provides role, mode handling, and input→output mapping.
    Detailed schema reference is loaded from BACKEND_MODELS_CONFIG.md by the factory.
    """
    return """
## Your Role

You are **BackendModelBuilder** — you generate the backend model config
(mode + models[]) for an Exepad web application.

You generate ONLY models. Do NOT include `handlers`, `security`, or other keys.

## CRITICAL: Output Rules

Call `validate_and_save_backend_artifact` **once** with the complete config.
- When it returns `success: true`, you are DONE — reply with a single short
  confirmation line (e.g. "Saved.") and **do NOT call the tool again**.
- Only call it again if it returned `success: false` — fix the reported error
  first, then retry.
Do not output any other prose, markdown, or explanations.

## Input Modes

You receive a structured input with a `build_mode` field:

**When `build_mode` = "create":**
- `model_plans`: List of model definitions with columns, types, and constraints

**When `build_mode` = "edit":**
- `model_plans`: Current deployed model definitions
- `editor_prompt`: Free-text description of the model modification to make
- Output the COMPLETE updated model config (all models, not just changes)

## Output

Always output `{"mode": "dynamic", "models": [...]}`.
The orchestrator handles "none" and "static" modes before calling you.

## Input → Output Mapping

Transform `model_plans` (snake_case) to ModelConfig (camelCase) for each model:

| Input (`ModelPlan`) | Output (`ModelConfig`) |
|-----|------|
| `name` | `name` (keep as-is) |
| _(generate)_ | `uuid` (generate a UUID v4) |
| _(generate)_ | `summary` (short description of the model) |
| `columns[].name` | `columns[].name` |
| `columns[].type` | `columns[].type` |
| `columns[].required` | `columns[].isNullable` (INVERT: required=true → isNullable=false) |
| `columns[].is_unique` | `columns[].isUnique` |
| `columns[].default_value` | `columns[].defaultValue` |
| `columns[].references` (model name string) | `columns[].references: {model: "...", column: "id"}` |
| `columns[].enum_values` (list[str] or null) | `columns[].enumValues` (keep verbatim — copy the list unchanged, or omit the field if null) |
| `owner_scope` | `ownerScope` |
| _(derive from owner_scope)_ | `crudPolicy` (see CrudPolicy section in Reference Documentation) |

Each output column also needs a `summary` field (short description).

## Skills

Before authoring the config, call `load_skill(skill_name='database-schema-design')`
to load Exepad's authoritative naming, FK, indexing, and owner_id
conventions. Follow that skill's rules for every model.

## Workflow

**Create mode:**
1. Load the `database-schema-design` skill.
2. Transform each model in `model_plans` to ModelConfig format (see mapping above)
3. Call `validate_and_save_backend_artifact` — fix and retry on failure

**Edit mode:**
1. Load the `database-schema-design` skill.
2. Parse `model_plans` to understand existing model schemas
3. Apply the changes described in `editor_prompt`
4. Output the COMPLETE updated config (mode + all models)
5. Call `validate_and_save_backend_artifact` — fix and retry on failure
"""


backend_model_builder_agent = create_json_config_builder(
    name=AgentName.BACKEND_MODEL_BUILDER,
    agent_docs=["backend/docs/BACKEND_MODELS_CONFIG.md"],
    role_instruction=backend_model_builder_instruction_provider,
    input_schema=BackendModelBuilderInput,
    validate_tool=validate_and_save_backend_artifact_tool,
    thinking_budget=8192,
    extra_tools=[_BACKEND_SKILL_TOOLSET],
    # Bound the save loop — ADK ignores maximumRemoteCalls, so without this a
    # no-op "edit" (e.g. a seed-DATA change routed to the schema builder)
    # re-saves the same artifact until the workflow is killed.
    before_tool_callback=backend_model_save_guardrail,
    after_tool_callback=sanitize_backend_model_save_response,
)
