// Pure renderers for the managed compose file, .env, and the version marker.
// Kept side-effect-free so they're trivially unit-testable; the CLI just writes
// whatever these return.
import {
  LAUNCHER_VERSION,
  IMAGE_REPO,
  CONTAINER_NAME,
  CADDY_IMAGE,
  CADDY_BUILDER_IMAGE,
  CADDY_DNS_DOCKERFILE,
  CADDY_ENV_FILE,
  DNS_TOKEN_ENV,
  DATA_VOLUME,
  CONTAINER_PORT,
  DEFAULT_HOST_PORT,
  caddyDnsModule,
  type TlsMode,
} from './config';
import { isDigest } from './version';

export interface DeployOptions {
  tag: string;
  hostPort?: number;
  /** When set, front the studio with a Caddy sidecar doing automatic HTTPS. */
  domain?: string;
  /** ACME contact email for Let's Encrypt (optional but recommended). */
  acmeEmail?: string;
  /** TLS strategy for the Caddy sidecar (only meaningful with `domain`). Default 'letsencrypt'. */
  tlsMode?: TlsMode;
  /** caddy-dns provider for `tlsMode: 'dns'` (e.g. 'cloudflare'). */
  dnsProvider?: string;
}

// Bound container logs so an `unless-stopped` studio can't fill the disk on a
// small self-host box (Docker's default json-file driver never rotates on its own).
// 4-space indented to sit under a compose service block.
const LOGGING_BLOCK =
  `    logging:\n` +
  `      driver: json-file\n` +
  `      options:\n` +
  `        max-size: "10m"\n` +
  `        max-file: "3"`;

/** Build the fully-qualified image reference, pinning a digest with `@` not `:`. */
export function imageRef(tag: string): string {
  if (tag.startsWith('@sha256:')) return `${IMAGE_REPO}${tag}`;
  if (tag.startsWith('sha256:')) return `${IMAGE_REPO}@${tag}`;
  return `${IMAGE_REPO}:${tag}`;
}

function pinNote(tag: string): string {
  return isDigest(tag)
    ? 'Pinned by digest (immutable).'
    : 'Pinned tag — never floats `:latest`. `exepad update` rewrites this ref.';
}

export function renderCompose(opts: DeployOptions): string {
  if (opts.domain) return renderComposeWithCaddy(opts);
  const port = opts.hostPort ?? DEFAULT_HOST_PORT;
  return `# Generated by exepad CLI v${LAUNCHER_VERSION}. Managed file. ${pinNote(opts.tag)}
# The studio serves plain HTTP on :${CONTAINER_PORT} for local/LAN use. For browser-trusted
# HTTPS on a real domain, rerun with \`exepad up --domain <your-domain>\`
# (adds an automatic-HTTPS Caddy sidecar). Do not expose :${port} straight to the
# internet — it is cleartext.
# Persistent state lives in the named volume "${DATA_VOLUME}" (/data), NOT in this directory.
services:
  ${CONTAINER_NAME}:
    image: ${imageRef(opts.tag)}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # This template publishes the studio's PLAIN-HTTP port as the front door, so the
      # in-image Caddy must stay OFF. Left on, the entrypoint marks session cookies
      # Secure (EXEPAD_COOKIE_SECURE=1) while terminating TLS on a container port this
      # file never publishes — the browser then REFUSES to store the cookie over
      # http://<lan-ip>:${port} and login silently fails everywhere except localhost
      # (which browsers treat as a secure context). Same reason as
      # deploy/docker-compose.yml and the app-store manifests.
      # Put a TLS-terminating proxy in front of :${port} (or use --domain) and the runtime
      # reads X-Forwarded-Proto and issues Secure cookies again. A Server & networking
      # panel override still wins over this env seed.
      - EXEPAD_HTTPS_DISABLE=1
    ports:
      - "${port}:${CONTAINER_PORT}"
    volumes:
      - ${DATA_VOLUME}:/data
${LOGGING_BLOCK}
volumes:
  ${DATA_VOLUME}:
    # Explicit name: compose would otherwise PREFIX the project (install-dir)
    # name, and backup/restore/docs mount the literal "exepad-data" — they
    # would silently hit an empty auto-created volume instead of the data.
    name: ${DATA_VOLUME}
`;
}

/** Header comment describing how the Caddy sidecar gets its certificate. */
function caddyComposeHeader(domain: string, mode: TlsMode): string {
  switch (mode) {
    case 'dns':
      return `# HTTPS for ${domain} via Caddy (Let's Encrypt DNS-01 — no inbound ports needed
# for issuance, works behind NAT). Caddy is rebuilt with a caddy-dns plugin; the DNS
# API token (${DNS_TOKEN_ENV}) lives in ./${CADDY_ENV_FILE}, read by Caddy only. The studio is internal-only.`;
    case 'byoc':
      return `# HTTPS for ${domain} via Caddy with YOUR OWN certificate (no ACME). Drop your
# cert at ./certs/cert.pem and key at ./certs/key.pem. The studio is internal-only;
# Caddy terminates TLS and proxies to it.`;
    default:
      return `# HTTPS for ${domain} via Caddy (automatic Let's Encrypt, HTTP-01). The studio is
# internal-only; Caddy is the sole public entry on :80/:443.`;
  }
}

/** The `caddy:` service body (4-space indented), varying by TLS strategy. */
function caddyServiceBlock(mode: TlsMode): string {
  // image vs build (DNS-01 needs a plugin-compiled Caddy).
  const imageOrBuild =
    mode === 'dns'
      ? `    build:\n      context: .\n      dockerfile: ${CADDY_DNS_DOCKERFILE}`
      : `    image: ${CADDY_IMAGE}`;
  // DNS-01 reads its token from a Caddy-only env file (kept out of the studio's .env
  // so the domain-controlling credential never reaches the app container).
  const caddyEnvFile =
    mode === 'dns' ? `    env_file:\n      - ./${CADDY_ENV_FILE}\n` : '';
  // BYOC mounts the operator's cert directory read-only.
  const certMount = mode === 'byoc' ? `      - ./certs:/etc/caddy/certs:ro\n` : '';
  return (
    `${imageOrBuild}\n` +
    `    container_name: ${CONTAINER_NAME}-caddy\n` +
    `    restart: unless-stopped\n` +
    `    depends_on:\n` +
    `      - ${CONTAINER_NAME}\n` +
    `    ports:\n` +
    `      - "80:80"\n` +
    `      - "443:443"\n` +
    caddyEnvFile +
    `    volumes:\n` +
    `      - ./Caddyfile:/etc/caddy/Caddyfile:ro\n` +
    certMount +
    `      - caddy-data:/data\n` +
    `      - caddy-config:/config\n` +
    LOGGING_BLOCK
  );
}

function renderComposeWithCaddy(opts: DeployOptions): string {
  const mode: TlsMode = opts.tlsMode ?? 'letsencrypt';
  return `# Generated by exepad CLI v${LAUNCHER_VERSION}. Managed file. ${pinNote(opts.tag)}
${caddyComposeHeader(opts.domain!, mode)}
# Persistent state lives in the named volume "${DATA_VOLUME}" (/data), NOT in this directory.
services:
  ${CONTAINER_NAME}:
    image: ${imageRef(opts.tag)}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "${CONTAINER_PORT}"
    volumes:
      - ${DATA_VOLUME}:/data
${LOGGING_BLOCK}
  caddy:
${caddyServiceBlock(mode)}
volumes:
  ${DATA_VOLUME}:
    name: ${DATA_VOLUME}  # literal name — see the non-domain template
  caddy-data:
  caddy-config:
`;
}

/**
 * The Caddyfile, varying by TLS strategy:
 *  - letsencrypt: bare `domain { reverse_proxy }` → Caddy auto-issues (HTTP-01).
 *  - dns:         `tls { dns <provider> {env.EXEPAD_DNS_TOKEN} }` → DNS-01 issuance.
 *  - byoc:        `auto_https off` + explicit `tls <cert> <key>` (no ACME) + :80 redirect.
 */
export function renderCaddyfile(
  domain: string,
  email?: string,
  mode: TlsMode = 'letsencrypt',
  dnsProvider?: string,
): string {
  const v = `# Generated by exepad CLI v${LAUNCHER_VERSION}.`;
  if (mode === 'byoc') {
    // Mirrors the proven repo root Caddyfile: static cert, no ACME machinery, plain
    // HTTP→HTTPS redirect (deliberately no HSTS so non-public/LAN access isn't pinned).
    return `${v} Bring-your-own-cert (internal CA / IT-issued). No ACME.
# Place your certificate at ./certs/cert.pem and private key at ./certs/key.pem.
{
\tauto_https off
}

:80 {
\tredir https://{host}{uri} permanent
}

:443 {
\ttls /etc/caddy/certs/cert.pem /etc/caddy/certs/key.pem
\treverse_proxy ${CONTAINER_NAME}:${CONTAINER_PORT}
}
`;
  }
  const global = email ? `{\n\temail ${email}\n}\n\n` : '';
  if (mode === 'dns') {
    const provider = dnsProvider ?? 'cloudflare';
    return `${v} Automatic HTTPS via Let's Encrypt (DNS-01 / ${provider}).
${global}${domain} {
\ttls {
\t\tdns ${provider} {env.${DNS_TOKEN_ENV}}
\t}
\treverse_proxy ${CONTAINER_NAME}:${CONTAINER_PORT}
}
`;
  }
  return `${v} Automatic HTTPS via Let's Encrypt.
${global}${domain} {
\treverse_proxy ${CONTAINER_NAME}:${CONTAINER_PORT}
}
`;
}

/**
 * Dockerfile that compiles Caddy with a single caddy-dns provider plugin, so the
 * DNS-01 Caddyfile's `dns <provider>` directive resolves. Built by
 * `docker compose up --build`. Two stages keep the runtime image slim.
 */
export function renderCaddyDnsDockerfile(provider: string): string {
  const module = caddyDnsModule(provider) ?? `github.com/caddy-dns/${provider}`;
  return `# Generated by exepad CLI v${LAUNCHER_VERSION} — Caddy + the ${provider} DNS plugin (DNS-01 ACME).
# Rebuilt on \`docker compose up --build\`. Base tags are pinned by the CLI's CADDY_* config.
FROM ${CADDY_BUILDER_IMAGE} AS build
RUN xcaddy build --with ${module}

FROM ${CADDY_IMAGE}
COPY --from=build /usr/bin/caddy /usr/bin/caddy
`;
}

// ---- .env (operator config only; platform secrets are generated in-container) ----

export type EnvUpdates = Record<string, string | undefined>;

const ENV_FLAG_MAP: Record<string, string> = {
  'llm-key': 'EXEPAD_LLM_API_KEY',
  'llm-provider': 'EXEPAD_LLM_PROVIDER',
  'llm-model': 'EXEPAD_LLM_MODEL_DEFAULT',
  'admin-email': 'EXEPAD_ADMIN_EMAIL',
  'admin-password': 'EXEPAD_ADMIN_PASSWORD',
};

export function envUpdatesFromFlags(flags: Record<string, unknown>): EnvUpdates {
  const updates: EnvUpdates = {};
  for (const [flag, key] of Object.entries(ENV_FLAG_MAP)) {
    const v = flags[flag];
    if (typeof v === 'string' && v.length > 0) updates[key] = v;
  }
  return updates;
}

export function parseEnv(text: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    map.set(line.slice(0, eq).trim(), line.slice(eq + 1));
  }
  return map;
}

export function hasEnvKey(existing: string, updates: EnvUpdates, key: string): boolean {
  if (typeof updates[key] === 'string' && updates[key]!.length > 0) return true;
  return parseEnv(existing).has(key);
}

/** Merge updates into an existing .env, preserving user-set keys and comments-as-data. */
export function mergeEnv(existing: string, updates: EnvUpdates): string {
  const map = parseEnv(existing);
  for (const [k, v] of Object.entries(updates)) {
    if (v !== undefined) map.set(k, v);
  }
  const header =
    '# Exepad operator config (managed by the exepad CLI).\n' +
    '# Safe to edit. Platform secrets are generated inside the /data volume, never here.';
  const body = [...map.entries()].map(([k, v]) => `${k}=${v}`).join('\n');
  return `${header}\n${body}\n`;
}

// ---- version marker ----

export interface VersionMarker {
  image: string;
  tag: string;
  launcher: string;
  hostPort: number;
  /** Present when the install fronts HTTPS with Caddy; preserved across updates. */
  domain?: string;
  acmeEmail?: string;
  /** TLS strategy ('dns' | 'byoc'); omitted for the default 'letsencrypt'. */
  tlsMode?: TlsMode;
  /** caddy-dns provider when tlsMode is 'dns'. */
  dnsProvider?: string;
  /**
   * Container engine this install was DEPLOYED under. The lifecycle verbs
   * prefer it over fresh detection so that installing Docker later on a
   * Podman-deployed host (or vice versa) can't silently point stop/backup/
   * restore at the wrong engine's containers and volumes (an engine mismatch
   * makes `backup` archive an EMPTY volume). Literal union rather than the
   * system.ts Engine type to keep compose.ts import-free of the probe layer.
   */
  engine?: 'docker' | 'podman';
  updatedAt: string;
}

export function renderVersionMarker(m: VersionMarker): string {
  // JSON.stringify drops undefined keys, so domain/acmeEmail only appear when set.
  return JSON.stringify(m, null, 2) + '\n';
}

export function parseVersionMarker(text: string): VersionMarker | null {
  try {
    const o = JSON.parse(text) as Partial<VersionMarker>;
    if (o && typeof o.tag === 'string') {
      return {
        image: typeof o.image === 'string' ? o.image : IMAGE_REPO,
        tag: o.tag,
        launcher: typeof o.launcher === 'string' ? o.launcher : '',
        hostPort: typeof o.hostPort === 'number' ? o.hostPort : DEFAULT_HOST_PORT,
        ...(typeof o.domain === 'string' ? { domain: o.domain } : {}),
        ...(typeof o.acmeEmail === 'string' ? { acmeEmail: o.acmeEmail } : {}),
        ...(typeof o.tlsMode === 'string' ? { tlsMode: o.tlsMode } : {}),
        ...(typeof o.dnsProvider === 'string' ? { dnsProvider: o.dnsProvider } : {}),
        ...(o.engine === 'docker' || o.engine === 'podman' ? { engine: o.engine } : {}),
        updatedAt: typeof o.updatedAt === 'string' ? o.updatedAt : '',
      };
    }
  } catch {
    /* not a marker */
  }
  return null;
}
