"""Generate a per-app TypeScript declaration file from backend manifest.

Output is a single ``app.d.ts`` that augments the ``@exepad/sdk`` module
with concrete model / handler / state / route names. ``tsc --noEmit``
then narrows the SDK's generic-typed hooks against the declared
identifiers and surfaces unknown names as compile-time errors.

The declaration uses the standard module-augmentation idiom: empty
interfaces in the SDK become non-empty when the app imports the
generated ``.d.ts``. Existing JS bundles are unaffected — only TypeScript
type-checking narrows.

Public entry: :func:`generate_app_dts`.
"""

from __future__ import annotations

from typing import Any


def generate_app_dts(
    *,
    backend: dict[str, Any] | None = None,
    logic: dict[str, Any] | None = None,
    pages: list[dict[str, Any]] | None = None,
    services: dict[str, Any] | None = None,
) -> str:
    """Build the per-app ``.d.ts`` text.

    Args:
        backend: ``backend.json`` manifest with ``models`` and
            ``handlers`` arrays.
        logic: ``logic.json`` manifest with a ``state`` dict.
        pages: List of page definitions; each entry has at least a
            ``slug``.
        services: legacy ``services`` dict from the assembled app config.
            No longer populated (the forms service was removed); the
            generator emits an empty ``AppForms`` interface regardless.

    Returns:
        Complete ``.d.ts`` source ready to write to a tempdir for
        ``tsc --noEmit``. Always emits a syntactically valid file even
        when every input is empty (in which case the augmentation is a
        no-op).
    """
    backend = backend or {}
    logic = logic or {}
    pages = pages or []
    services = services or {}

    model_lines = _model_interfaces(backend.get("models") or [])
    handler_lines = _handler_interfaces(backend.get("handlers") or [])
    state_lines = _state_interface(logic.get("state") or {})
    route_line = _route_alias(pages)
    form_lines = _form_interface((services.get("forms") or {}).get("definitions") or [])

    body = _MODULE_TEMPLATE.format(
        models=model_lines or "  // (no models declared)",
        handler_outputs=handler_lines or "  // (no handlers declared)",
        state_keys=state_lines or "  // (no state keys declared)",
        routes=route_line,
        forms=form_lines or "  // (no forms registered)",
    )
    return _HEADER + body


_HEADER = """\
/**
 * Per-app TypeScript declarations — generated by
 * services/validation/tsc_validator/dts_generator.py.
 *
 * Augments @exepad/sdk with concrete model / handler / state / route
 * names so tsc --noEmit narrows useModel('foo') against the declared
 * catalog. Do not edit by hand; regenerate per workflow.
 */

"""

_MODULE_TEMPLATE = """\
declare module '@exepad/sdk' {{
  interface AppModels {{
{models}
  }}

  interface AppHandlerOutputs {{
{handler_outputs}
  }}

  interface AppState {{
{state_keys}
  }}

  interface AppRoutes {{
{routes}
  }}

  interface AppForms {{
{forms}
  }}
}}

export {{}};
"""


def _ts_field_type(field: Any) -> str:
    """Map a backend column / handler output type to a TypeScript type.

    Supported type strings (case-insensitive):

    - Primitives: ``string``/``text``/``uuid``/``email``/``url``/``date``/
      ``datetime``/``timestamp`` → ``string``;
      ``number``/``int``/``integer``/``float``/``decimal``/``real``/
      ``currency``/``percent``/``percentage``/``ratio`` → ``number``;
      ``bool``/``boolean`` → ``boolean``.
    - ``json``/``object`` → ``any``. Loose on purpose: handlers commonly
      declare json-shaped outputs (``{name: "foo", type: "json"}``) when
      the inner shape isn't worth pinning. Mapping to
      ``Record<string, unknown>`` *blocks* common access patterns (``.length``,
      ``.map``, field reads), forcing the LLM into ``(data as unknown as X)``
      triple-casts that defeat the whole point of typing. ``any`` matches
      the existing run-time semantics (the value is whatever the SQL
      driver returned) and keeps the generated component tsc-clean.
    - ``array`` (no element type) → ``unknown[]`` — caller knows it's a
      list but element shape wasn't declared.
    - ``array<X>`` — element-typed array. ``X`` may be:
      - a primitive (``array<string>`` → ``string[]``),
      - a model name (``array<articles>`` → ``AppModels['articles'][]``;
        emitted bare because this declaration is inside the
        ``declare module '@exepad/sdk'`` augmentation block).
    """
    if isinstance(field, dict):
        type_str = (field.get("type") or "").strip()
    else:
        type_str = str(field).strip()
    lowered = type_str.lower()
    if lowered in {"string", "text", "uuid", "email", "url", "date", "datetime", "timestamp"}:
        return "string"
    if lowered in {
        "number",
        "int",
        "integer",
        "float",
        "decimal",
        "real",
        "currency",
        "percent",
        "percentage",
        "ratio",
    }:
        return "number"
    if lowered in {"bool", "boolean"}:
        return "boolean"
    if lowered in {"json", "object"}:
        return "any"
    if lowered == "array":
        return "unknown[]"
    if lowered.startswith("array<") and lowered.endswith(">"):
        # Preserve the original (non-lowercased) inner so model names like
        # ``Articles`` keep their case, even though the overall keyword
        # match is case-insensitive.
        inner = type_str[len("array<") : -1].strip()
        return f"{_array_element_to_ts(inner)}[]"
    return "unknown"


def _array_element_to_ts(inner: str) -> str:
    """Resolve the element type inside ``array<...>`` to a TS type."""
    primitives = {
        "string": "string",
        "text": "string",
        "uuid": "string",
        "email": "string",
        "url": "string",
        "date": "string",
        "datetime": "string",
        "timestamp": "string",
        "number": "number",
        "int": "number",
        "integer": "number",
        "float": "number",
        "decimal": "number",
        "real": "number",
        "currency": "number",
        "percent": "number",
        "percentage": "number",
        "ratio": "number",
        "bool": "boolean",
        "boolean": "boolean",
        "json": "any",
        "object": "any",
        "any": "any",
        "unknown": "unknown",
    }
    lowered = inner.lower()
    if lowered in primitives:
        return primitives[lowered]
    # Any bare identifier we don't recognize — assume it's a declared
    # model name and look it up via ``AppModels``. tsc resolves this at
    # type-check time; if the model isn't actually declared, the index
    # access will surface as a TS2536 — better than silently widening
    # to ``unknown`` and burying the planning miss.
    if inner.replace("_", "").isalnum():
        return f"AppModels['{inner}']"
    # Anything else (e.g. inline shape) — fall back to ``unknown``. We
    # could parse ``{a: number, b: string}`` shapes here, but that's a
    # follow-up: the comma in the parser used by ``_build_handler_metadata``
    # currently splits on ``,`` and would mangle inline-object literals.
    return "unknown"


# System fields the platform's auto-CRUD layer always provides on every
# row, regardless of whether the model schema declares them. Components
# routinely use ``row.id`` (e.g. ``key={item.id}`` in a .map()) and
# timestamps; without these in the row type tsc fires TS2339 on every
# such access. The app-backend injects all four on insert.
#
# ``id`` is ``number`` because the platform's ``DEFAULT_PRIMARY_KEY``
# (packages/deploy-utils/src/schema/types.ts) is ``INTEGER PRIMARY KEY
# AUTOINCREMENT`` and the SeedDataBuilder system prompt forces seed rows
# to use integer ids starting at 1. FK columns declared as ``integer``
# (e.g. ``attendance.member_id``) therefore match the parent ``id`` at
# runtime; the prior ``("id", "string")`` made tsc reject natural JOIN
# patterns like ``attendance.find(a => a.member_id === member.id)``.
# A model that explicitly declares ``id: text`` (rare, e.g. UUID-keyed
# shared tables) wins via the ``declared`` override below.
_SYSTEM_ROW_FIELDS: tuple[tuple[str, str], ...] = (
    ("id", "number"),
    ("created_at", "string"),
    ("updated_at", "string"),
    ("owner_id", "string"),
)


def _model_interfaces(models: list[dict[str, Any]]) -> str:
    """Emit interface entries for each declared model.

    Format:
        users: { id: string; created_at: string; updated_at: string;
                 owner_id: string; name: string; email: string };

    System fields (``id``, ``created_at``, ``updated_at``, ``owner_id``)
    are always present even when the model schema doesn't declare them —
    they're injected by the auto-CRUD layer. Declared fields override
    the system defaults so an explicit ``id: number`` schema wins.

    Auto-join sibling fields: for every ``<X>_id`` column whose
    ``references.model`` points to another declared model in the same
    backend, an optional ``<X>?: AppModels['<Target>'] | null`` field is
    added. This mirrors the runtime auto-CRUD behaviour documented in
    ``crud_data_app.md`` (every FK gets a sibling joined row attached
    to each result row, named by stripping the ``_id`` suffix). Without
    this emission ``tsc`` rejects compliant LLM code like
    ``row.guest?.full_name`` with TS2339 ("Property 'guest' does not
    exist…"), shipping unresolved type errors as warnings. See app
    ``ky3clhzb`` post-mortem.
    """
    declared_names = {
        m.get("name")
        for m in models
        if isinstance(m, dict) and isinstance(m.get("name"), str) and m.get("name")
    }

    lines: list[str] = []
    for model in models:
        if not isinstance(model, dict):
            continue
        name = model.get("name")
        if not isinstance(name, str) or not name:
            continue
        cols = model.get("columns") or model.get("fields") or []
        declared: dict[str, str] = {}
        joined_siblings: list[tuple[str, str]] = []
        for col in cols:
            if isinstance(col, dict):
                cname = col.get("name")
                ctype = _ts_field_type(col)
                nullable = col.get("nullable") or col.get("optional")
                if cname:
                    suffix = " | null" if nullable else ""
                    declared[cname] = f"{ctype}{suffix}"
                # Auto-join sibling: <X>_id with references.model pointing
                # to another declared model produces an optional sibling
                # field named <X> typed as the target model's row.
                refs = col.get("references")
                if (
                    isinstance(refs, dict)
                    and isinstance(cname, str)
                    and cname.endswith("_id")
                    and len(cname) > len("_id")
                ):
                    target = refs.get("model")
                    if isinstance(target, str) and target in declared_names and target != name:
                        sibling_name = cname[: -len("_id")]
                        # Don't shadow a declared field of the same name.
                        if sibling_name and sibling_name not in declared:
                            joined_siblings.append((sibling_name, f"AppModels['{target}'] | null"))
            elif isinstance(col, str) and col:
                # ``"name: type"`` shorthand.
                if ":" in col:
                    cname, ctype_str = (s.strip() for s in col.split(":", 1))
                    declared[cname] = _ts_field_type(ctype_str)
                else:
                    declared[col] = "unknown"
        # System fields fill in only where the schema didn't declare a
        # field of the same name.
        merged: list[tuple[str, str]] = []
        seen: set[str] = set()
        for sys_name, sys_type in _SYSTEM_ROW_FIELDS:
            if sys_name in declared:
                merged.append((sys_name, declared[sys_name]))
            else:
                merged.append((sys_name, sys_type))
            seen.add(sys_name)
        for cname, ctype in declared.items():
            if cname not in seen:
                merged.append((cname, ctype))
                seen.add(cname)
        for sib_name, sib_type in joined_siblings:
            if sib_name in seen:
                continue
            # Optional `?:` so existing code that only reads `*_id` still
            # type-checks without forcing every consumer to handle the
            # joined row.
            merged.append((f"{sib_name}?", sib_type))
            seen.add(sib_name)
        body = "; ".join(f"{n}: {t}" for n, t in merged)
        lines.append(f"    {name}: {{ {body} }};")
    return "\n".join(lines)


def _handler_interfaces(handlers: list[dict[str, Any]]) -> str:
    """Emit interface entries for each declared handler's output shape."""
    lines: list[str] = []
    for handler in handlers:
        if not isinstance(handler, dict):
            continue
        name = handler.get("name")
        if not isinstance(name, str) or not name:
            continue
        outputs = handler.get("outputs") or []
        # Detect array-shaped output: the handler returns ``T[]`` only when
        # its entire output IS an array — signalled by a single *nameless*
        # ``type: "array"`` (or ``type: "array<X>"``) entry. A multi-field
        # output that happens to include an array-typed field describes
        # ONE object whose field is array-shaped, NOT an array of objects.
        #
        # Past behaviour wrapped the whole shape in ``[]`` whenever any
        # field was array-typed — which broke real handlers like
        # ``getDashboardStats`` returning ``{tco: number, chartData: T[]}``
        # by typing the return as ``{tco: number, chartData: T[]}[]``, so
        # components reading ``stats.tco`` failed tsc and retried.
        is_array = _output_is_top_level_array(outputs)
        field_strs: list[str] = []
        for out in outputs:
            if isinstance(out, dict):
                oname = out.get("name")
                otype = _ts_field_type(out)
                if oname:
                    field_strs.append(f"{oname}: {otype}")
            elif isinstance(out, str) and ":" in out:
                oname, otype_str = (s.strip() for s in out.split(":", 1))
                field_strs.append(f"{oname}: {_ts_field_type(otype_str)}")
        if not field_strs:
            shape = "Record<string, unknown>"
        else:
            shape = "{ " + "; ".join(field_strs) + " }"
        if is_array:
            shape = f"{shape}[]"
        lines.append(f"    {name}: {shape};")
    return "\n".join(lines)


def _output_is_top_level_array(outputs: list[Any]) -> bool:
    """True when ``outputs`` declares the handler returns a top-level array.

    Top-level-array shape requires a single nameless output of type
    ``array`` or ``array<X>``. Multi-field outputs (even when one field
    is array-typed) describe a single object, not an array of objects.

    Accepts both dict form ``{"type": "array"}`` and string form
    ``"array"`` / ``"array<modelName>"``.
    """
    if len(outputs) != 1:
        return False
    only = outputs[0]
    if isinstance(only, dict):
        if only.get("name"):
            return False
        type_str = only.get("type") or ""
    elif isinstance(only, str):
        # Named string form is ``"name: type"`` — reject anything with a colon.
        if ":" in only:
            return False
        type_str = only.strip()
    else:
        return False
    if not isinstance(type_str, str):
        return False
    base = type_str.split("<", 1)[0].strip()
    return base == "array"


def _state_interface(state: dict[str, Any]) -> str:
    """Emit interface entries for each declared state key.

    ``setState`` is always emitted as the first member — it is part of
    the real SDK's ``AppState`` (``packages/exepad-sdk/src/platform/useApp.ts``)
    but the gate's ``agent_sdk_gate.d.ts`` declares ``AppState`` as an
    empty stub, so per-app augmentation must restore it. Without this,
    ``useApp(s => s.setState)`` slipped through validation as
    ``unknown`` member access on apps like ``n1aloggh``.
    """
    lines: list[str] = ["    setState: (key: string, value: unknown) => void;"]
    for key, value in state.items():
        if not isinstance(key, str) or not key:
            continue
        ts_type = _state_value_type(value)
        lines.append(f"    {key}: {ts_type};")
    return "\n".join(lines)


def _state_value_type(value: Any) -> str:
    """Best-effort mapping from a sample state value to a TypeScript type."""
    if value is None:
        return "unknown"
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, (int, float)):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        return "unknown[]"
    if isinstance(value, dict):
        return "Record<string, unknown>"
    return "unknown"


def _route_alias(pages: list[dict[str, Any]]) -> str:
    """Build the ``AppRoutes`` interface entries from declared page slugs.

    Augments ``interface AppRoutes`` in the SDK with one ``'<slug>': true``
    entry per declared page. ``keyof AppRoutes`` then resolves to the
    union of declared paths, narrowing ``navigate(...)``'s constraint.
    """
    slugs: list[str] = []
    for page in pages:
        if not isinstance(page, dict):
            continue
        slug = page.get("slug")
        if not isinstance(slug, str):
            continue
        # Defensive strip — DesignImporter LLM occasionally emits page_route
        # with surrounding whitespace (e.g. `" /"` for the homepage). Without
        # this, the union literal carries the space and rejects the
        # whitespace-free `'/'` the runtime actually ships.
        normalized = slug.strip()
        if normalized:
            slugs.append(normalized)
    if not slugs:
        return "    // (no routes declared)"
    deduped = sorted(set(slugs))
    return "\n".join(f"    '{s}': true;" for s in deduped)


def _form_interface(definitions: list[Any]) -> str:
    """Build the ``AppForms`` interface entries from a legacy ``services``
    payload.

    The platform no longer ships a forms service, so ``services.forms`` is
    never populated and this returns the empty placeholder. Retained so the
    generated ``.d.ts`` stays structurally stable for older app configs.
    """
    ids: list[str] = []
    for entry in definitions:
        if isinstance(entry, dict):
            fid = entry.get("id")
        elif isinstance(entry, str):
            fid = entry
        else:
            continue
        if isinstance(fid, str) and fid.strip():
            ids.append(fid.strip())
    if not ids:
        return ""
    deduped = sorted(set(ids))
    return "\n".join(f"    '{fid}': {{}};" for fid in deduped)
