"""Run ``tsc --noEmit`` against a generated component.

Per-component flow (called from ``syntax_validator`` as Stage 1.5):

1. Write the component source to a tempdir as ``Component.tsx``.
2. Write the generated per-app ``app.d.ts`` next to it.
3. Copy the SDK's public types (``packages/exepad-sdk/src/index.ts``)
   so module augmentation resolves.
4. Write a minimal ``tsconfig.json`` that includes both files.
5. Invoke ``tsc --noEmit`` (timeout 10 s).
6. Parse stdout / stderr lines into :class:`Finding` objects.

Graceful fallbacks:
- ``tsc`` binary not present (``FileNotFoundError``) → returns ``[]``
  in development (local dev without Node.js stays unblocked).
  **Production raises** :class:`ProductionDependencyMissing` so a
  misconfigured container fails its health check rather than serving
  with type-checking silently disabled. See
  ``services/validation/_env.py``.
- ``tsconfig`` template missing → returns ``[]`` and logs a warning.
- Subprocess timeout (>10 s) → returns a single Finding noting the
  failure rather than crashing the workflow.
"""

from __future__ import annotations

import json
import re
import subprocess
import tempfile
from pathlib import Path
from typing import Iterable

import structlog

from main_agent.services.validation._env import require_in_production
from main_agent.services.validation.finding import Finding
from main_agent.services.validation.safe_names import is_safe_artifact_name
from main_agent.services.validation.tsx_ast.catalog import ALLOWED_EXTENSION_IMPORTS

logger = structlog.get_logger(__name__)


_TSC_TIMEOUT_SECONDS = 10
_TSC_DIAGNOSTIC_RE = re.compile(
    r"^(?P<file>[^()]+)\((?P<line>\d+),(?P<col>\d+)\):\s+"
    r"error\s+TS(?P<code>\d+):\s+(?P<msg>.+)$"
)
_AGENT_SDK_GATE_DTS = Path(__file__).resolve().parent / "agent_sdk_gate.d.ts"

# Additive SDK subpath entries (mirror packages/exepad-sdk/src/entries/*.ts and
# the import-map keys in apps/runtime/client/index.html). These are stable
# architecture names, not symbols — the per-symbol routing lives in
# sdk-subpaths.json. Each is staged as a re-export of the bare gate module so
# tsc resolves ``@exepad/sdk/<entry>`` imports emitted by the split fixer.
_SDK_SUBPATH_ENTRIES: tuple[str, ...] = (
    "core",
    "charts",
    "motion",
    "forms",
    "overlays",
    "icons",
)


_TSCONFIG_TEMPLATE = {
    "compilerOptions": {
        "target": "ES2022",
        "module": "ESNext",
        "moduleResolution": "Bundler",
        "jsx": "react-jsx",
        "strict": True,
        # noImplicitAny is disabled — LLM-generated event handlers
        # commonly leave the event parameter untyped (``(e) => ...``).
        # The TS7006 false-positive cost a retry per affected component
        # in production; the safety gain (catching genuine type-confusion
        # bugs in agent-emitted code) is small relative to that cost.
        # strictNullChecks stays on (catches ``useModel().data`` null
        # bugs and similar real issues).
        "noImplicitAny": False,
        "noEmit": True,
        "skipLibCheck": True,
        "esModuleInterop": True,
        "allowSyntheticDefaultImports": True,
        "isolatedModules": True,
        "lib": ["ES2022", "DOM", "DOM.Iterable"],
    },
    "include": ["./*.tsx", "./*.ts", "./*.d.ts"],
}


# Minimal React types so ``"jsx": "react-jsx"`` doesn't error with
# ``Cannot find module 'react/jsx-runtime'`` (TS2875) or
# ``no interface 'JSX.IntrinsicElements' exists`` (TS7026) on every
# component. We don't ship ``@types/react`` in the agent container —
# the gate's value is checking ``useModel`` / ``useHandler`` /
# ``setState`` / ``Icons.*`` against the per-app manifest, not
# validating that ``<div>`` accepts ``className``. Making everything
# ``any`` here strips JSX type-checking but keeps the cross-reference
# checks intact (those run on identifiers in expressions, not on JSX).
_REACT_SHIM_DTS = """\
// Auto-generated by tsc_validator/runner.py — do not edit by hand.
// Provides just enough React/JSX surface for tsc to parse generated
// components without infrastructure errors. Real type-safety lives in
// the per-app app.d.ts (model/handler/state/route narrowing).

declare namespace JSX {
  interface IntrinsicElements {
    [elemName: string]: any;
  }
  interface Element {
    [k: string]: any;
  }
  interface ElementClass {
    [k: string]: any;
  }
  interface ElementAttributesProperty {
    props: {};
  }
  interface ElementChildrenAttribute {
    children: {};
  }
  interface IntrinsicAttributes {
    key?: any;
  }
}

declare module "react/jsx-runtime" {
  export const Fragment: any;
  export function jsx(type: any, props: any, key?: any): any;
  export function jsxs(type: any, props: any, key?: any): any;
}

declare module "react/jsx-dev-runtime" {
  export const Fragment: any;
  export function jsxDEV(
    type: any,
    props: any,
    key?: any,
    isStaticChildren?: boolean,
    source?: any,
    self?: any,
  ): any;
}

// React namespace + module — both forms have to exist together so that
// type positions like ``React.SyntheticEvent`` and value positions like
// ``React.useState`` and ``import React from 'react'`` all resolve
// without errors. Mirrors the structure @types/react ships:
// the namespace carries the type / value catalogue, and the module
// declares ``export = React`` so default and namespace imports both
// reach the namespace.
declare namespace React {
  // ---- Type catalogue (used in annotation / generic / cast positions)
  type ReactNode = any;
  type ReactElement<P = any> = any;
  type ReactPortal = any;
  type ReactFragment = any;
  type FC<P = any> = any;
  type FunctionComponent<P = any> = any;
  type ComponentType<P = any> = any;
  type ComponentClass<P = any> = any;
  type ComponentProps<T = any> = any;
  type PropsWithChildren<P = any> = any;
  type PropsWithoutRef<P = any> = any;
  type CSSProperties = any;
  type Key = any;
  type Ref<T = any> = any;
  type RefObject<T = any> = any;
  type MutableRefObject<T = any> = any;
  type RefCallback<T = any> = any;
  type ForwardedRef<T = any> = any;
  type Dispatch<T = any> = any;
  type SetStateAction<T = any> = any;
  type EffectCallback = any;
  type DependencyList = any;
  type Reducer<S = any, A = any> = any;
  type ReducerState<R = any> = any;
  type ReducerAction<R = any> = any;
  type Context<T = any> = any;
  type Provider<T = any> = any;
  type Consumer<T = any> = any;

  // Event types (the most common React.* pattern in generated TSX)
  type SyntheticEvent<T = any, E = any> = any;
  type ChangeEvent<T = any> = any;
  type FormEvent<T = any> = any;
  type MouseEvent<T = any, E = any> = any;
  type KeyboardEvent<T = any> = any;
  type FocusEvent<T = any, E = any> = any;
  type ClipboardEvent<T = any> = any;
  type DragEvent<T = any> = any;
  type WheelEvent<T = any> = any;
  type TouchEvent<T = any> = any;
  type PointerEvent<T = any> = any;
  type AnimationEvent<T = any> = any;
  type TransitionEvent<T = any> = any;
  type CompositionEvent<T = any> = any;
  type UIEvent<T = any> = any;
  type EventHandler<E = any> = any;

  // HTML / DOM attribute helpers
  type HTMLAttributes<T = any> = any;
  type DOMAttributes<T = any> = any;
  type AriaAttributes = any;
  type HTMLProps<T = any> = any;
  type DetailedHTMLProps<E = any, T = any> = any;
  type AllHTMLAttributes<T = any> = any;
  type AnchorHTMLAttributes<T = any> = any;
  type ButtonHTMLAttributes<T = any> = any;
  type InputHTMLAttributes<T = any> = any;
  type SelectHTMLAttributes<T = any> = any;
  type TextareaHTMLAttributes<T = any> = any;
  type ImgHTMLAttributes<T = any> = any;
  type SVGAttributes<T = any> = any;
  type SVGProps<T = any> = any;

  // ---- Value catalogue (used in expression positions:
  //      ``React.useState(0)``, ``<React.Fragment>``, etc.)
  const Fragment: any;
  const StrictMode: any;
  const Suspense: any;
  const Profiler: any;
  const Children: any;

  function useState<S = any>(initial?: S | (() => S)): [S, (v: S | ((prev: S) => S)) => void];
  function useEffect(effect: any, deps?: any[]): void;
  function useLayoutEffect(effect: any, deps?: any[]): void;
  function useMemo<T = any>(factory: () => T, deps?: any[]): T;
  function useCallback<T = any>(cb: T, deps?: any[]): T;
  // ``initial?: T | null`` matches the @types/react canonical signature.
  // Real React's ``useRef<HTMLDivElement>(null)`` is the universal idiom;
  // ``T | undefined`` would reject the literal ``null`` the LLM emits.
  function useRef<T = any>(initial?: T | null): { current: T };
  function useContext<T = any>(ctx: any): T;
  function useReducer<S = any, A = any>(
    reducer: any,
    initial: S,
    init?: any,
  ): [S, (action: A) => void];
  function useImperativeHandle(ref: any, init: any, deps?: any[]): void;
  function useDeferredValue<T = any>(value: T): T;
  function useTransition(): [boolean, (cb: () => void) => void];
  function useId(): string;

  function createContext<T = any>(defaultValue: T): any;
  function createElement(type: any, props?: any, ...children: any[]): any;
  function cloneElement(element: any, props?: any, ...children: any[]): any;
  function isValidElement(value: any): boolean;
  function memo<T = any>(component: T, propsAreEqual?: any): T;
  function forwardRef<T = any, P = any>(render: any): any;
  function lazy<T = any>(factory: () => Promise<T>): any;

  // Catch-all for anything we missed — hooks, helpers, internal slots.
  // Keeps tsc permissive without enumerating the full @types/react surface.
  const __anything__: any;
}

declare module "react" {
  export = React;
}

declare module "react-dom" {
  const ReactDOM: any;
  export = ReactDOM;
}

declare module "react-dom/client" {
  export const createRoot: any;
  export const hydrateRoot: any;
}
"""


# Shorthand ambient declarations for the vetted runtime extension packages
# (``@exepad/ext-three`` etc.). A body-less ``declare module "X";`` makes the
# whole module ``any`` — so ``import * as THREE from "@exepad/ext-three"`` and
# any member access (``THREE.WebGLRenderer``, ``THREE.Raycaster``, …) type-check
# without TS2307 ("cannot find module") or TS2339 ("property does not exist").
# This mirrors the runtime reality: ``packages/exepad-sdk/src/ext.d.ts`` types
# every extension member as ``any`` too. Built from the SAME allow-list the AST
# import rule uses (``ALLOWED_EXTENSION_IMPORTS``) so the gate and the rule can
# never disagree about which extensions are admissible.
_EXT_SHIM_DTS = (
    "// Auto-generated by tsc_validator/runner.py — do not edit by hand.\n"
    "// Ambient `any` modules for the vetted @exepad/ext-* extension packages.\n"
    + "".join(f'declare module "{spec}";\n' for spec in sorted(ALLOWED_EXTENSION_IMPORTS))
)


def run_tsc_check(
    *,
    tsx: str,
    component_name: str,
    app_dts: str,
    sibling_modules: dict[str, str] | None = None,
) -> list[Finding]:
    """Run ``tsc --noEmit`` against ``tsx`` + ``app_dts``.

    Args:
        tsx: Component source. Saved as ``<component_name>.tsx``.
        component_name: PascalCase identifier — also the file basename.
        app_dts: Generated per-app declaration file (from
            :func:`dts_generator.generate_app_dts`).
        sibling_modules: Optional Babel-shell sibling map
            ``{ModuleName: tsx_source}``. When provided, each sibling is
            staged as ``<ModuleName>.tsx`` in the same tmpdir so that
            ``import { X } from "./ModuleName"`` references resolve
            naturally and don't surface as TS2307 false positives. The
            target component's own name is filtered out defensively
            (passing the target in the dict is harmless). Findings from
            sibling files are filtered by ``_parse_diagnostics`` (which
            already restricts to the target file's diagnostics) so
            sibling-internal type errors don't leak into the gate.

    Returns:
        List of :class:`Finding`. Each TS diagnostic that survives the
        skip-lib pass becomes one Finding with rule_id
        ``"tsc.<TS-code>"`` and severity ``"error"``. Empty list when
        ``tsc`` isn't available, when both inputs are empty, or when
        the SDK type bundle can't be located.
    """
    if not tsx.strip():
        return []

    if not _AGENT_SDK_GATE_DTS.is_file():
        logger.warning(
            "tsc_validator: agent_sdk_gate.d.ts not found — skipping tsc gate",
            expected=str(_AGENT_SDK_GATE_DTS),
        )
        return []

    # Path-traversal guard: component_name is an LLM-controlled free-form string
    # that becomes a filename on disk. A name like `../../../../tmp/pwned` would
    # escape the tempdir. Skip the tsc gate (fail open on validation) rather than
    # write outside it — the save path rejects the name hard at artifact_tools.
    if not is_safe_artifact_name(component_name):
        logger.warning(
            "tsc_validator: unsafe component name, skipping tsc gate",
            name=component_name,
        )
        return []

    with tempfile.TemporaryDirectory(prefix="tsc-gate-") as tmpdir:
        tmp = Path(tmpdir)
        component_path = tmp / f"{component_name}.tsx"
        component_path.write_text(tsx, encoding="utf-8")
        (tmp / "app.d.ts").write_text(app_dts, encoding="utf-8")
        # React/JSX shim (+ extension ambient modules) — picked up by
        # tsconfig's ``"include": ["./*.d.ts"]``. Without the React shim tsc
        # errors with TS2875 / TS7026 on every component; the ``@exepad/ext-*``
        # ambient ``any`` modules let 3D/WebGL components import Three.js etc.
        # without TS2307 (same allow-list as the AST import rule).
        (tmp / "react-shim.d.ts").write_text(_REACT_SHIM_DTS + _EXT_SHIM_DTS, encoding="utf-8")

        # Stage Babel-shell siblings so ``import { X } from "./Sibling"``
        # resolves on disk instead of surfacing as TS2307. The target
        # itself is filtered out so we never overwrite the file we just
        # wrote at component_path. Sibling-internal type errors are
        # filtered out downstream by _parse_diagnostics, which restricts
        # findings to the target file's diagnostics.
        for sib_name, sib_tsx in (sibling_modules or {}).items():
            if sib_name == component_name:
                continue
            if not isinstance(sib_name, str) or not isinstance(sib_tsx, str):
                continue
            # Same traversal guard for sibling names before they hit the disk.
            if not is_safe_artifact_name(sib_name):
                continue
            if not sib_tsx.strip():
                continue
            (tmp / f"{sib_name}.tsx").write_text(sib_tsx, encoding="utf-8")

        # Stage the curated SDK gate declaration under a node_modules
        # layout so ``import ... from "@exepad/sdk"`` resolves to our
        # typed surface (useModel/useHandler/setState/navigate
        # constraints, JSX components as `any`).
        #
        # Subpaths: the ``component_sdk_subpaths`` auto-fixer rewrites the bare
        # barrel into ``@exepad/sdk/core``, ``@exepad/sdk/charts``, … imports.
        # Each subpath ``.d.ts`` just re-exports the ambient gate module, and
        # the ``exports`` map lets ``moduleResolution: Bundler`` find them — so
        # ``useModel('x')`` narrowing still flows through (verified) and a
        # mistyped subpath name surfaces as TS2307 rather than silently passing.
        sdk_dir = tmp / "node_modules" / "@exepad" / "sdk"
        sdk_dir.mkdir(parents=True, exist_ok=True)
        (sdk_dir / "index.d.ts").write_bytes(_AGENT_SDK_GATE_DTS.read_bytes())
        exports_map: dict[str, dict[str, str]] = {".": {"types": "./index.d.ts"}}
        for entry in _SDK_SUBPATH_ENTRIES:
            (sdk_dir / f"{entry}.d.ts").write_text(
                'export * from "@exepad/sdk";\n', encoding="utf-8"
            )
            exports_map[f"./{entry}"] = {"types": f"./{entry}.d.ts"}
        (sdk_dir / "package.json").write_text(
            json.dumps({"name": "@exepad/sdk", "types": "index.d.ts", "exports": exports_map}),
            encoding="utf-8",
        )

        (tmp / "tsconfig.json").write_text(
            json.dumps(_TSCONFIG_TEMPLATE, indent=2),
            encoding="utf-8",
        )

        try:
            result = subprocess.run(
                ["tsc", "--noEmit", "--project", str(tmp / "tsconfig.json")],
                capture_output=True,
                text=True,
                timeout=_TSC_TIMEOUT_SECONDS,
                cwd=str(tmp),
            )
        except FileNotFoundError:
            # Production fails loud: the Dockerfile vendors Node + tsc, so a
            # missing binary means the container is misconfigured. Dev
            # continues to fail open so contributors without Node.js can
            # iterate on the rest of the pipeline.
            require_in_production(
                dependency="tsc",
                hint=(
                    "The Dockerfile vendors Node.js + tsc — a missing "
                    "binary means the container build is broken. Refusing "
                    "to validate components with no type-check."
                ),
            )
            return []
        except subprocess.TimeoutExpired:
            return [
                Finding(
                    rule_id="tsc.timeout",
                    severity="error",
                    message=(
                        f"tsc --noEmit timed out (>{_TSC_TIMEOUT_SECONDS}s) "
                        f"on {component_name} — check for circular type imports"
                    ),
                    line=1,
                    col=0,
                )
            ]

        if result.returncode == 0:
            return []
        return list(_parse_diagnostics(result.stdout, component_name))


def _parse_diagnostics(stdout: str, component_name: str) -> Iterable[Finding]:
    """Convert tsc's stdout into Finding objects."""
    for line in stdout.splitlines():
        m = _TSC_DIAGNOSTIC_RE.match(line.strip())
        if m is None:
            continue
        file_name = m.group("file").strip()
        # Only surface diagnostics from the user's component file.
        # Library / SDK type-issue diagnostics are filtered by
        # ``skipLibCheck`` already; this guards against any leftover.
        if not file_name.endswith(f"{component_name}.tsx"):
            continue
        yield Finding(
            rule_id=f"tsc.{m.group('code')}",
            severity="error",
            message=m.group("msg").strip(),
            line=int(m.group("line")),
            col=int(m.group("col")),
        )
