/**
 * Admin Source Routes — read-only access to an app's generated source code.
 *
 *   GET /            — list the source file tree (config-referenced files only)
 *   GET /file?path=  — fetch one source file's text (path must be in the tree)
 *   GET /download    — download the whole source tree as a .zip
 *
 * "Source" = the human-authored TSX/CSS/CSV the agent wrote for THIS app (the
 * assembled `app_config.json` is read to drive enumeration but is NOT itself
 * exposed — it is config, not source). Enumeration is driven by the app's live
 * config (`repo.*` source refs), NOT a raw storage prefix walk:
 *
 *   - Builds overwrite source keys in place and never delete renamed/removed
 *     files, so a `{appId}/code/` prefix walk would surface stale "orphan"
 *     source from prior builds. Driving off the live config yields exactly the
 *     files the current app references.
 *   - It is also naturally clean of secrets and other users' data: compiled
 *     output, version/published snapshots, the per-app SQLite DB, `meta.sqlite`,
 *     and `/data/secrets` all live outside the config's source refs.
 *   - And it avoids `FsStorageAdapter.list()`, which walks the ENTIRE storage
 *     root and filters by prefix (O(all-apps)); a handful of `head()`/`get()`
 *     calls keyed off the config is O(this-app).
 *
 * Auth: owner-only via {@link operatorOwnsApp} (the operator's platform-session
 * cookie must own the app in `meta.sqlite`). We deliberately do NOT use
 * `authenticateAdmin` here — it provisions a SQLite database as a side effect,
 * which a read-only source browse must never trigger.
 */
import { Hono } from 'hono';
import { zipSync, strToU8 } from 'fflate';
import type { Env } from '../../types/env';
import { operatorOwnsApp } from '../../lib/admin-auth';
import {
  MAX_ZIP_BYTES,
  TEXT_EXTS,
  ext,
  enumerateSource,
  appNameOf,
  slug,
  type SourceEntry,
} from '../../lib/export/source-set';

export const source = new Hono<{ Bindings: Env }>();

function buildReadme(appName: string, entries: SourceEntry[]): string {
  const list = entries.map((e) => `- \`${e.path}\``).join('\n');
  return `# ${appName} — source code (read-only export)

This is a faithful, **read-only** snapshot of the source the Exepad agent
generated for this app, exported from the Studio. It is **not** a standalone,
installable project: the components depend on Exepad's in-house SDK surface
(\`useApp\`, \`useModel\`, \`useHandler\`, …), Tailwind v4 \`@layer\` scoping, and the
platform's auto-CRUD backend, none of which are vendored here.

## Contents

${list || '- (no source files found)'}

## Layout

Only folders this app actually uses appear under **Contents** above. Their roles:

- \`code/frontend/components/\` — React (TSX) components rendered in the app.
- \`code/frontend/styles/\` — theme stylesheet source.
- \`code/backend/handlers/\` — server-side handler source (only if the app has handlers).
- \`repo/seed/\` — seed datasets (CSV).

Generated by Exepad Studio.
`;
}

// ── GET / — list the source file tree ────────────────────────
source.get('/', async (c) => {
  const appId = c.req.param('appId')!;
  if (!(await operatorOwnsApp(c.req.raw, c.env, appId))) {
    return c.json({ success: false, error: 'Unauthorized' }, 401);
  }

  const { configRaw, entries } = await enumerateSource(c.env, appId);
  if (configRaw == null) {
    return c.json(
      { success: false, error: 'No source is available for this app yet. Build it first.' },
      404,
    );
  }

  const files = entries.map((e) => ({ path: e.path, size: e.size }));
  return c.json({ success: true, data: { files, appName: appNameOf(configRaw) } });
});

// ── GET /file?path= — fetch a single source file's text ──────
source.get('/file', async (c) => {
  const appId = c.req.param('appId')!;
  if (!(await operatorOwnsApp(c.req.raw, c.env, appId))) {
    return c.json({ success: false, error: 'Unauthorized' }, 401);
  }

  const rawPath = c.req.query('path') ?? '';
  const { configRaw, entries } = await enumerateSource(c.env, appId);
  if (configRaw == null) {
    return c.json({ success: false, error: 'No source available.' }, 404);
  }

  // Membership in the enumerated set IS the authorization + traversal guard:
  // only live, config-referenced source paths are reachable.
  const entry = entries.find((e) => e.path === rawPath);
  if (!entry) return c.json({ success: false, error: 'File not found' }, 404);

  if (!TEXT_EXTS.has(ext(entry.path))) {
    return c.json({ success: false, error: 'Binary file — use the .zip download.' }, 415);
  }

  const obj = await c.env.CONFIG_CACHE.get(entry.key);
  if (!obj) return c.json({ success: false, error: 'File not found' }, 404); // raced with a rebuild
  const text = await obj.text();
  return new Response(text, {
    status: 200,
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
});

// ── GET /download — whole source tree as a .zip ──────────────
source.get('/download', async (c) => {
  const appId = c.req.param('appId')!;
  if (!(await operatorOwnsApp(c.req.raw, c.env, appId))) {
    return c.json({ success: false, error: 'Unauthorized' }, 401);
  }

  const { configRaw, entries } = await enumerateSource(c.env, appId);
  if (configRaw == null) {
    return c.json({ success: false, error: 'No source available.' }, 404);
  }

  const appName = appNameOf(configRaw);
  const files: Record<string, Uint8Array> = {};
  let total = 0;

  const readme = strToU8(buildReadme(appName, entries));
  files['README.md'] = readme;
  total += readme.length;

  for (const e of entries) {
    const obj = await c.env.CONFIG_CACHE.get(e.key);
    if (!obj) continue; // raced with a rebuild — skip rather than fail the whole zip
    const buf = new Uint8Array(await obj.arrayBuffer());
    if (total + buf.length > MAX_ZIP_BYTES) {
      return c.json(
        { success: false, error: 'Source is too large to download as a single zip.' },
        413,
      );
    }
    total += buf.length;
    files[e.path] = buf;
  }

  // Build the zip in THIS module (where fflate lives) and return it directly.
  // Hand the Response a plain ArrayBuffer slice — the generic Uint8Array type
  // doesn't satisfy the workers-types BodyInit union.
  const zipped = zipSync(files, { level: 6 });
  const body = zipped.buffer.slice(
    zipped.byteOffset,
    zipped.byteOffset + zipped.byteLength,
  ) as ArrayBuffer;
  // The read-only mirror must not collide with the buildable-project export
  // (`/export/source` → `<slug>-source.zip`); a regular user can download both.
  const filename = `${slug(appName)}-source-mirror.zip`;
  return new Response(body, {
    status: 200,
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Content-Length': String(zipped.length),
      'Cache-Control': 'no-store',
    },
  });
});
