"""Final Tailwind compile gate — deterministic, no-LLM, runs once at workflow end.

Stages 1 (esbuild syntax), 1.5 (tsc), 2 (semantic + auto-fix) and 4
(style coverage) all run inline by the component save tool. This module
owns the only cross-component step left — the Tailwind v4 compile of
``theme.css`` + every component's classnames into the final stylesheet.

Public entry: :func:`run_final_compile_gate`.

Pipeline:

1. Lift any nested ``@import``/``@source`` directives out of ``@layer``
   blocks (Tailwind v4 rejects them).
2. Lift any nested ``@utility`` blocks to top level (same reason).
3. Ensure the Tailwind bootstrap directives are present at the top of
   theme.css (LLM design imports occasionally drop them).
4. Run ``tailwindcss --input theme.css --output compiled.css`` against
   a temp directory containing all components.
5. If the compile fails, attempt the deterministic ``@apply`` strip and
   the bare-comma syntax fixers as second-chance recovery.
6. Return a :class:`CompileResult` with compiled CSS or fatal errors.
   No retries, no LLM regeneration — the caller decides whether a fatal
   compile error blocks deploy.

The deterministic CSS fixers (``_strip_unknown_apply_classes``,
``_fix_css_syntax_errors``, the lift/inject helpers) are inlined here
because they only run inside this gate.
"""

from __future__ import annotations

import os
import re
import subprocess
import tempfile
from dataclasses import dataclass, field

import structlog

from main_agent.services.validation.safe_names import (
    assert_inside_dir,
    is_safe_artifact_name,
)

logger = structlog.get_logger(__name__)

TAILWIND_BASE_CSS = """\
@import "tailwindcss";
@import "tw-animate-css";
@source "./components";
"""

# ---------------------------------------------------------------------------
# SDK overlay component safelist
# ---------------------------------------------------------------------------
# Tailwind CSS is compiled from component .tsx files only. SDK UI components
# (Dialog, Sheet, AlertDialog, Popover, Tooltip, DropdownMenu, ContextMenu,
# Drawer, HoverCard) use internal Tailwind classes that are NOT in component
# source. This synthetic TSX is added to the content scan so Tailwind emits
# the necessary overlay/portal CSS classes.
# ---------------------------------------------------------------------------
_SDK_OVERLAY_CLASSES_TSX = """\
// Synthetic file — SDK overlay component classes for Tailwind content scanning.
// DO NOT EDIT — generated by final_compile_gate.py.
//
// Dialog / AlertDialog overlay
// className="fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0"
// Dialog / AlertDialog content — motion now lives in `.exepad-dialog-content`
// (see _DIALOG_MOTION_CSS below), so only the static layout utilities need
// content-scan coverage here; the enter/exit keyframes are authored CSS.
// className="exepad-dialog-content fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg sm:rounded-lg"
// Dialog close button
// className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground"
// Dialog header / footer
// className="flex flex-col space-y-1.5 text-center sm:text-left"
// className="flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2"
// Dialog title / description
// className="text-lg font-semibold leading-none tracking-tight"
// className="text-sm text-muted-foreground"
//
// Sheet overlay (same as Dialog)
// Sheet content variants
// className="fixed z-50 gap-4 bg-background p-6 shadow-lg transition ease-in-out data-[state=closed]:duration-300 data-[state=open]:duration-500 data-[state=open]:animate-in data-[state=closed]:animate-out"
// className="inset-x-0 top-0 border-b data-[state=closed]:slide-out-to-top data-[state=open]:slide-in-from-top"
// className="inset-x-0 bottom-0 border-t data-[state=closed]:slide-out-to-bottom data-[state=open]:slide-in-from-bottom"
// className="inset-y-0 left-0 h-full w-3/4 border-r data-[state=closed]:slide-out-to-left data-[state=open]:slide-in-from-left sm:max-w-sm"
// className="inset-y-0 right-0 h-full w-3/4 border-l data-[state=closed]:slide-out-to-right data-[state=open]:slide-in-from-right sm:max-w-sm"
// Sheet close button
// className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-secondary"
//
// Popover
// className="z-50 w-72 rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2"
//
// Tooltip
// className="z-50 overflow-hidden rounded-md bg-primary px-3 py-1.5 text-xs text-primary-foreground animate-in fade-in-0 zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2"
//
// DropdownMenu / ContextMenu content
// className="z-50 min-w-[8rem] overflow-hidden rounded-md border bg-popover p-1 text-popover-foreground shadow-lg data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2"
// Menu items
// className="relative flex cursor-default select-none items-center gap-2 rounded-sm px-2 py-1.5 text-sm outline-none transition-colors focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50"
// className="relative flex cursor-default select-none items-center rounded-sm py-1.5 pl-8 pr-2 text-sm outline-none focus:bg-accent focus:text-accent-foreground data-[disabled]:pointer-events-none data-[disabled]:opacity-50"
// Menu separator
// className="-mx-1 my-1 h-px bg-muted"
// className="-mx-1 my-1 h-px bg-border"
// Menu shortcut
// className="ml-auto text-xs tracking-widest opacity-60"
//
// Drawer overlay
// className="fixed inset-0 z-50 bg-black/80"
// Drawer content
// className="grid gap-1.5 p-4 text-center sm:text-left"
// className="mt-auto flex flex-col gap-2 p-4"
//
// HoverCard
// className="z-50 w-64 rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2"
//
// AlertDialog action/cancel button states
// className="mt-2 sm:mt-0"
//
// Shared icon sizes used by close buttons
// className="h-4 w-4"
// className="h-3.5 w-3.5"
// className="sr-only"
//
// Switch (Radix)
// className="peer inline-flex h-5 w-9 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input"
// className="pointer-events-none block h-4 w-4 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-4 data-[state=unchecked]:translate-x-0"
"""


# ---------------------------------------------------------------------------
# Dialog motion CSS
# ---------------------------------------------------------------------------
# The SDK Dialog/AlertDialog panels tag their content element with
# ``.exepad-dialog-content`` and (optionally) ``data-exepad-motion="<preset>"``
# instead of hardcoding tw-animate-css utilities. This block supplies the
# actual enter/exit keyframes, so every generated app ships them regardless of
# what the design system's theme.css contains.
#
# The animation is DRIVEN BY THE APP'S DESIGN TOKENS — ``--animation-scale-enter``
# and ``--animation-slide-enter`` (emitted on ``:root`` by DesignSystemBuilder,
# and inherited by the portaled dialog) actually change the panel's transform,
# so each app's motion personality differs instead of every dialog sharing one
# hardcoded fade+zoom. A ``motion`` prop on a single dialog overrides that
# per-app default via the ``data-exepad-motion`` presets below.
#
# Injected into the CSS *compile input* only (see ``_base_css_for_compile``);
# it is deliberately NOT written back into the stored theme.css, so it can't
# compound across edit turns. Authored CSS (keyframes + literal selectors)
# passes through Tailwind v4 verbatim. Kept in sync with the SDK's own
# ``packages/exepad-sdk/src/index.css`` copy.
# ---------------------------------------------------------------------------
_DIALOG_MOTION_CSS = """\
/* Exepad dialog motion — token-driven, per-dialog overridable.
   DO NOT EDIT compiled output; source lives in final_compile_gate.py. */
@keyframes exepad-dialog-enter {
  from {
    opacity: 0;
    transform:
      translate(-50%, calc(-50% + var(--exepad-dialog-slide, var(--animation-slide-enter, 8px))))
      scale(var(--exepad-dialog-scale, var(--animation-scale-enter, 0.95)));
  }
  to { opacity: 1; transform: translate(-50%, -50%) scale(1); }
}
@keyframes exepad-dialog-exit {
  from { opacity: 1; transform: translate(-50%, -50%) scale(1); }
  to {
    opacity: 0;
    transform:
      translate(-50%, calc(-50% + var(--exepad-dialog-slide, var(--animation-slide-enter, 8px))))
      scale(var(--exepad-dialog-scale, var(--animation-scale-enter, 0.95)));
  }
}
.exepad-dialog-content[data-state="open"] {
  animation: exepad-dialog-enter var(--animation-duration, 200ms)
    var(--animation-ease, cubic-bezier(0.4, 0, 0.2, 1)) both;
}
.exepad-dialog-content[data-state="closed"] {
  animation: exepad-dialog-exit var(--animation-duration, 200ms)
    var(--animation-ease, cubic-bezier(0.4, 0, 0.2, 1)) both;
}
.exepad-dialog-content[data-exepad-motion="fade"]       { --exepad-dialog-scale: 1;    --exepad-dialog-slide: 0px; }
.exepad-dialog-content[data-exepad-motion="zoom"]       { --exepad-dialog-scale: 0.95; --exepad-dialog-slide: 0px; }
.exepad-dialog-content[data-exepad-motion="scale"]      { --exepad-dialog-scale: 0.9;  --exepad-dialog-slide: 0px; }
.exepad-dialog-content[data-exepad-motion="pop"]        { --exepad-dialog-scale: 0.85; --exepad-dialog-slide: 0px; }
.exepad-dialog-content[data-exepad-motion="slide-up"]   { --exepad-dialog-scale: 1;    --exepad-dialog-slide: 16px; }
.exepad-dialog-content[data-exepad-motion="slide-down"] { --exepad-dialog-scale: 1;    --exepad-dialog-slide: -16px; }
.exepad-dialog-content[data-exepad-motion="none"]       { animation: none !important; }
@media (prefers-reduced-motion: reduce) {
  .exepad-dialog-content[data-state="open"],
  .exepad-dialog-content[data-state="closed"] { animation-duration: 1ms !important; }
}
"""


def _base_css_for_compile(base_css: str) -> str:
    """Append the deterministic dialog-motion CSS to the Tailwind compile input.

    Kept out of ``base_css`` / ``rewritten_theme_css`` so the motion block is a
    pure compile-time addition (like the synthetic overlay-class file) and never
    accumulates in the stored theme.css across edit turns.
    """
    return f"{base_css}\n\n{_DIALOG_MOTION_CSS}"


# ---------------------------------------------------------------------------
# Bare-display-utility safelist
# ---------------------------------------------------------------------------
# Tailwind v4's content scanner is unreliable for bare display utilities
# (``md:flex``, ``md:hidden`` etc.) when they sit next to hyphenated siblings
# in the same className string. Observed on pnkndvyy (2026-05-15): MainSidebar
# emits ``"hidden md:flex flex-col h-full ..."`` but compiled.css ships
# ``.md\:flex-row{...}`` without ``.md\:flex{display:flex}`` — the sidebar
# resolves to ``display: none`` at every breakpoint.
#
# Listing each utility explicitly here lets Tailwind's scanner pick it up
# regardless of the className adjacency hazard. The data-* attributes alongside
# keep the entry shaped like real component source so v4's tokenizer treats
# each className substring as a complete utility.
# ---------------------------------------------------------------------------
_DISPLAY_VARIANTS_TSX = """\
// Synthetic file — bare responsive display utilities for Tailwind scanning.
// DO NOT EDIT — generated by final_compile_gate.py.
// Without these, ``md:flex`` / ``md:hidden`` / etc. sometimes don't compile
// when sourced from a className adjacent to a hyphenated sibling.
//
// className="flex"
// className="block"
// className="inline"
// className="inline-block"
// className="grid"
// className="hidden"
// className="sm:flex"
// className="sm:block"
// className="sm:inline"
// className="sm:inline-block"
// className="sm:grid"
// className="sm:hidden"
// className="md:flex"
// className="md:block"
// className="md:inline"
// className="md:inline-block"
// className="md:grid"
// className="md:hidden"
// className="lg:flex"
// className="lg:block"
// className="lg:inline"
// className="lg:inline-block"
// className="lg:grid"
// className="lg:hidden"
// className="xl:flex"
// className="xl:block"
// className="xl:inline"
// className="xl:inline-block"
// className="xl:grid"
// className="xl:hidden"
// className="2xl:flex"
// className="2xl:block"
// className="2xl:inline"
// className="2xl:inline-block"
// className="2xl:grid"
// className="2xl:hidden"
"""

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_NON_FATAL_PATTERNS = [
    "caniuse-lite is outdated",
    "browserslist",
    "update-browserslist-db",
]

_CLASS_NOT_FOUND_RE = re.compile(
    r"(?:The `([^`]+)` class does not exist" r"|Cannot apply unknown utility class `([^`]+)`)"
)
_CSS_SYNTAX_ERROR_RE = re.compile(r"base\.css:(\d+):(\d+):\s*(.*)")

_BOOTSTRAP_LAYER_RE = re.compile(r"@layer\b[^{;]*\{")
_BOOTSTRAP_DIRECTIVE_RE = re.compile(r"@(?:import|source)\b[^;{}]*;")

_UTILITY_MARKER = "@utility"
_EXEPAD_APP_LAYER_RE = re.compile(r"@layer\s+exepad-app\s*\{")


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------


@dataclass
class CompileResult:
    """Outcome of the final Tailwind compile gate."""

    compiled_css: str = ""
    fatal_errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    fixes_applied: list[str] = field(default_factory=list)
    rewritten_theme_css: str | None = None
    """Set when deterministic CSS fixers rewrote the input. The caller
    should persist this rewritten theme.css back to the artifact store
    so subsequent loads see the canonicalised content."""

    @property
    def success(self) -> bool:
        return not self.fatal_errors


# ---------------------------------------------------------------------------
# Public entry
# ---------------------------------------------------------------------------


def run_final_compile_gate(
    *,
    theme_css: str,
    tsx_sources: dict[str, str],
) -> CompileResult:
    """Run the final Tailwind compile against the workflow's complete output.

    Args:
        theme_css: Final ``codefocus_style:theme.css`` content (after all
            ``add_theme_tokens`` mutations). The deterministic CSS fixers
            may rewrite it; the rewritten content is returned via
            ``CompileResult.rewritten_theme_css``.
        tsx_sources: Map of ``component_name -> tsx_content`` for every
            component the workflow produced.

    Returns:
        :class:`CompileResult`. ``success`` is True iff Tailwind compiled
        cleanly (after the deterministic recovery passes). The caller
        decides whether ``fatal_errors`` blocks deploy or surfaces as
        warnings.
    """
    if not tsx_sources:
        return CompileResult(warnings=["No components to compile"])

    fixes: list[str] = []
    warnings: list[str] = []
    rewritten_theme: str | None = None

    base_css = theme_css

    # Pre-fix #1: lift @import / @source out of @layer { ... }.
    base_css, lifted_directives = _lift_nested_bootstrap_directives(base_css)
    if lifted_directives:
        warnings.append(
            f"Lifted {lifted_directives} nested @import/@source directive(s) "
            "out of @layer (Tailwind v4 rejects them otherwise)"
        )
        rewritten_theme = base_css

    # Pre-fix #2: ensure the bootstrap directives are present.
    base_css, bootstrap_added = _ensure_tailwind_bootstrap(base_css)
    if bootstrap_added:
        warnings.append(
            "Prepended Tailwind v4 bootstrap directives to theme.css "
            "(builder omitted @import/@source)"
        )
        rewritten_theme = base_css

    # Pre-fix #2.5: prefix bare property names inside @theme blocks. The
    # DesignImporter occasionally emits ``font-mono: ...`` instead of
    # ``--font-mono: ...``; Tailwind v4 rejects bare names in @theme.
    base_css, theme_prop_fixes = _prefix_theme_custom_properties(base_css)
    if theme_prop_fixes:
        fixes.extend(theme_prop_fixes)
        rewritten_theme = base_css

    with tempfile.TemporaryDirectory() as tmpdir:
        base_path = _write_file(tmpdir, "base.css", _base_css_for_compile(base_css))
        tsx_dir = os.path.join(tmpdir, "components")
        os.makedirs(tsx_dir)
        used_filenames: set[str] = set()
        for idx, (name, tsx) in enumerate(tsx_sources.items()):
            filename_stem = name
            if not is_safe_artifact_name(filename_stem):
                # Workflow-generated synthetic keys (e.g. "__module__/Card") carry
                # a '/' so they stay unique in the source map; they are NOT
                # LLM-controlled. Dropping them here meant their className tokens
                # never reached the Tailwind scanner, so supporting-module classes
                # rendered unstyled. Sanitize to a safe on-disk stem (with an index
                # suffix to guarantee uniqueness) instead of skipping. Names that
                # can't be sanitized to a bare identifier are still refused.
                sanitized = re.sub(r"[^A-Za-z0-9_]", "_", str(name)).strip("_")
                candidate = f"__src_{idx}_{sanitized}" if sanitized else f"__src_{idx}"
                if not is_safe_artifact_name(candidate):
                    logger.warning("final_compile_gate: skipping unsafe source name", name=name)
                    continue
                filename_stem = candidate
            # Guard against collisions after sanitization (two distinct keys must
            # not overwrite each other and drop one module's class tokens).
            if filename_stem in used_filenames:
                filename_stem = f"{filename_stem}_{idx}"
            used_filenames.add(filename_stem)
            _write_file(tsx_dir, f"{filename_stem}.tsx", tsx)
        _write_file(tsx_dir, "_sdk_overlay_classes.tsx", _SDK_OVERLAY_CLASSES_TSX)
        _write_file(tsx_dir, "_display_variants.tsx", _DISPLAY_VARIANTS_TSX)

        css_output = os.path.join(tmpdir, "compiled.css")
        success, compiled_css, errors = _compile_css(tsx_dir, base_path, css_output)

        # Pre-fix #3: lift nested @utility blocks (last-ditch).
        if not success:
            lifted_css, lifted_count = _lift_nested_utility_blocks(base_css)
            if lifted_count:
                warnings.append(f"Lifted {lifted_count} nested @utility block(s) to top level")
                base_css = lifted_css
                rewritten_theme = base_css
                _write_file(tmpdir, "base.css", _base_css_for_compile(base_css))
                success, compiled_css, errors = _compile_css(tsx_dir, base_path, css_output)

        # Pre-fix #4: strip @apply lines referencing unknown classes.
        if not success:
            cleaned_css, stripped = _strip_unknown_apply_classes(base_css, errors)
            if stripped:
                fixes.append(
                    f"Stripped {len(stripped)} @apply line(s) referencing unknown "
                    f"classes: {', '.join(sorted(set(stripped)))}"
                )
                base_css = cleaned_css
                rewritten_theme = base_css
                _write_file(tmpdir, "base.css", _base_css_for_compile(base_css))
                success, compiled_css, errors = _compile_css(tsx_dir, base_path, css_output)

        # Pre-fix #5: bare-comma / trailing-comma syntax repairs.
        if not success:
            repaired_css, syntax_fixes = _fix_css_syntax_errors(base_css, errors)
            if syntax_fixes:
                fixes.extend(syntax_fixes)
                base_css = repaired_css
                rewritten_theme = base_css
                _write_file(tmpdir, "base.css", _base_css_for_compile(base_css))
                success, compiled_css, errors = _compile_css(tsx_dir, base_path, css_output)

        if success:
            return CompileResult(
                compiled_css=compiled_css,
                warnings=warnings,
                fixes_applied=fixes,
                rewritten_theme_css=rewritten_theme,
            )
        return CompileResult(
            fatal_errors=errors,
            warnings=warnings,
            fixes_applied=fixes,
            rewritten_theme_css=rewritten_theme,
        )


# ---------------------------------------------------------------------------
# Deterministic CSS fixers — second-chance recovery passes when Tailwind's
# initial compile fails. No LLM; pattern-based rewrites only.
# ---------------------------------------------------------------------------


_THEME_BLOCK_OPEN_RE = re.compile(r"@theme\b[^{]*\{")
_BARE_PROP_LINE_RE = re.compile(r"^([a-zA-Z][a-zA-Z0-9-]*)\s*:")


def _prefix_theme_custom_properties(css: str) -> tuple[str, list[str]]:
    """Prefix bare property names inside ``@theme`` blocks with ``--``.

    Tailwind v4 rejects ``@theme { font-mono: ...; }`` with
    ``@theme blocks must only contain custom properties or @keyframes``.
    The DesignImporter occasionally drops the ``--`` prefix on tokens it
    introduces from the source design (font-mono is the recurring
    offender). This healer scans every ``@theme {...}`` block, walks its
    direct children, and prefixes any bare property declaration.

    Brace depth is tracked so contents of nested ``@keyframes`` blocks
    (which legitimately use bare names like ``transform``) are left
    intact.

    Args:
        css: Theme CSS source.

    Returns:
        ``(rewritten_css, fixes)`` — fixes is a list of human-readable
        messages describing each rewrite, suitable for logging.
    """
    fixes: list[str] = []
    out: list[str] = []
    i = 0
    n = len(css)

    while i < n:
        m = _THEME_BLOCK_OPEN_RE.search(css, i)
        if m is None:
            out.append(css[i:])
            break

        # Emit everything up to and including the opening ``@theme {``.
        out.append(css[i : m.end()])
        block_start = m.end()

        # Find the matching close brace, tracking nested blocks.
        depth = 1
        j = block_start
        while j < n and depth > 0:
            ch = css[j]
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    break
            j += 1

        if depth != 0:
            # Unbalanced braces — bail out and emit the rest verbatim.
            out.append(css[block_start:])
            break

        body = css[block_start:j]
        rewritten, body_fixes = _rewrite_theme_block_body(body)
        out.append(rewritten)
        out.append("}")
        fixes.extend(body_fixes)
        i = j + 1

    return "".join(out), fixes


def _rewrite_theme_block_body(body: str) -> tuple[str, list[str]]:
    """Walk an ``@theme`` body line-by-line; prefix top-level property
    declarations that lack the ``--`` prefix.

    Lines inside nested rules (``@keyframes`` typically) are detected
    via brace-depth tracking and emitted unchanged.
    """
    fixes: list[str] = []
    out_lines: list[str] = []
    depth = 0

    for line in body.splitlines(keepends=True):
        if depth == 0:
            stripped = line.lstrip()
            # Skip lines that start with ``@`` (nested at-rules), ``--``
            # (already-prefixed properties), comments, and blank lines.
            if (
                stripped
                and not stripped.startswith("@")
                and not stripped.startswith("--")
                and not stripped.startswith("/*")
                and not stripped.startswith("//")
            ):
                m = _BARE_PROP_LINE_RE.match(stripped)
                if m:
                    name = m.group(1)
                    indent = line[: len(line) - len(stripped)]
                    rest = stripped[m.end() :]
                    out_lines.append(f"{indent}--{name}:{rest}")
                    fixes.append(f"@theme: prefixed `{name}:` → `--{name}:`")
                    depth += line.count("{") - line.count("}")
                    continue

        out_lines.append(line)
        depth += line.count("{") - line.count("}")

    return "".join(out_lines), fixes


def _strip_unknown_apply_classes(css: str, errors: list[str]) -> tuple[str, list[str]]:
    """Strip ``@apply`` lines referencing non-existent Tailwind classes."""
    classes_to_strip: set[str] = set()
    for error in errors:
        m = _CLASS_NOT_FOUND_RE.search(error)
        if m:
            # Tailwind v3 captures into group(1); v4 into group(2).
            classes_to_strip.add(m.group(1) or m.group(2))
    if not classes_to_strip:
        return css, []

    stripped: list[str] = []
    cleaned_lines: list[str] = []
    for line in css.split("\n"):
        should_strip = False
        if "@apply" in line:
            for cls in classes_to_strip:
                if cls in line:
                    should_strip = True
                    # Record every unknown class on the line so the
                    # caller's user-facing message lists them all.
                    stripped.append(cls)
        if not should_strip:
            cleaned_lines.append(line)
    return "\n".join(cleaned_lines), list(set(stripped))


def _fix_css_syntax_errors(css: str, errors: list[str]) -> tuple[str, list[str]]:
    """Regex-based recovery for bare comma / trailing comma CSS syntax errors."""
    error_locs: list[tuple[int, int, str]] = []
    for err in errors:
        m = _CSS_SYNTAX_ERROR_RE.search(err)
        if m:
            error_locs.append((int(m.group(1)), int(m.group(2)), m.group(3)))
    if not error_locs:
        return css, []

    lines = css.split("\n")
    fixes: list[str] = []
    for line_no, col, _msg in sorted(error_locs, key=lambda x: x[0], reverse=True):
        idx = line_no - 1
        if idx < 0 or idx >= len(lines):
            continue
        line = lines[idx]
        if line.strip() == ",":
            lines.pop(idx)
            fixes.append(f"Removed bare comma at line {line_no}")
            continue
        stripped = line.rstrip()
        if stripped.endswith(",") and ":" in stripped:
            lines[idx] = stripped[:-1]
            fixes.append(f"Removed trailing comma at line {line_no}")
            continue
        col_idx = col - 1
        if 0 <= col_idx < len(line) and line[col_idx] == ",":
            lines[idx] = line[:col_idx] + line[col_idx + 1 :]
            if not lines[idx].strip():
                lines.pop(idx)
            fixes.append(f"Removed stray comma at line {line_no}:{col}")
    return "\n".join(lines), fixes


def _find_block_end(src: str, open_brace_idx: int) -> int:
    """Return index of matching ``}`` for ``{`` at ``open_brace_idx`` (or -1)."""
    depth = 0
    i = open_brace_idx
    n = len(src)
    while i < n:
        ch = src[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return -1


def _strip_directives_from_layer_body(body: str) -> tuple[str, list[str]]:
    """Remove ``@import``/``@source`` lines from a layer body."""
    new_parts: list[str] = []
    lifted: list[str] = []
    last = 0
    for dm in _BOOTSTRAP_DIRECTIVE_RE.finditer(body):
        new_parts.append(body[last : dm.start()])
        lifted.append(dm.group(0).strip())
        last = dm.end()
        while last < len(body) and body[last] in " \t":
            last += 1
        if last < len(body) and body[last] == "\n":
            last += 1
    new_parts.append(body[last:])
    return "".join(new_parts), lifted


def _lift_nested_bootstrap_directives(css: str) -> tuple[str, int]:
    """Lift ``@import``/``@source`` directives that appear inside ``@layer``."""
    if "@layer" not in css:
        return css, 0
    if "@import" not in css and "@source" not in css:
        return css, 0

    out_parts: list[str] = []
    lifted: list[str] = []
    cursor = 0
    for m in _BOOTSTRAP_LAYER_RE.finditer(css):
        if m.start() < cursor:
            continue
        body_open = m.end() - 1
        body_close = _find_block_end(css, body_open)
        if body_close == -1:
            break
        body = css[body_open + 1 : body_close]
        if "@import" not in body and "@source" not in body:
            continue
        cleaned_body, body_lifted = _strip_directives_from_layer_body(body)
        if not body_lifted:
            continue
        out_parts.append(css[cursor : body_open + 1])
        out_parts.append(cleaned_body)
        cursor = body_close
        lifted.extend(body_lifted)

    if not lifted:
        return css, 0

    out_parts.append(css[cursor:])
    rewritten = "".join(out_parts)
    to_prepend: list[str] = []
    seen: set[str] = set()
    for d in lifted:
        if d in seen or d in rewritten:
            continue
        seen.add(d)
        to_prepend.append(d)
    if not to_prepend:
        return rewritten, len(lifted)
    return "\n".join(to_prepend) + "\n\n" + rewritten.lstrip(), len(lifted)


def _is_utility_at_index(src: str, i: int) -> bool:
    """True if ``src[i:]`` starts with the ``@utility`` at-rule keyword."""
    n = len(src)
    if not src.startswith(_UTILITY_MARKER, i):
        return False
    if i > 0 and (src[i - 1].isalnum() or src[i - 1] in "_-"):
        return False
    after = i + len(_UTILITY_MARKER)
    if after < n and src[after].isalnum():
        return False
    return True


def _find_nested_utility_spans(css: str) -> list[tuple[int, int]]:
    """Return spans of every ``@utility {...}`` block at depth > 0."""
    spans: list[tuple[int, int]] = []
    depth = 0
    i = 0
    n = len(css)
    while i < n:
        ch = css[i]
        if ch == "{":
            depth += 1
            i += 1
            continue
        if ch == "}":
            depth -= 1
            i += 1
            continue
        if not _is_utility_at_index(css, i):
            i += 1
            continue
        ob = css.find("{", i)
        if ob == -1:
            break
        be = _find_block_end(css, ob)
        if be == -1:
            break
        if depth > 0:
            spans.append((i, be + 1))
        i = be + 1
    return spans


def _splice_out_spans(css: str, spans: list[tuple[int, int]]) -> str:
    """Remove the given spans from ``css``, consuming a trailing newline."""
    rewritten = css
    for start, end_excl in reversed(spans):
        ee = end_excl
        if ee < len(rewritten) and rewritten[ee] == "\n":
            ee += 1
        rewritten = rewritten[:start] + rewritten[ee:]
    return rewritten


def _inject_after_exepad_layer(rewritten: str, inject: str) -> str:
    """Insert ``inject`` after the outermost ``@layer exepad-app`` block."""
    lm = _EXEPAD_APP_LAYER_RE.search(rewritten)
    if not lm:
        return rewritten.rstrip() + "\n\n" + inject + "\n"
    layer_close = _find_block_end(rewritten, lm.end() - 1)
    if layer_close == -1:
        return rewritten.rstrip() + "\n\n" + inject + "\n"
    after = layer_close + 1
    tail = rewritten[after:]
    existing = tail.find(_UTILITY_MARKER)
    if existing != -1:
        split = after + existing
        return rewritten[:split] + inject + "\n\n" + rewritten[split:]
    return rewritten[:after].rstrip() + "\n\n" + inject + "\n" + rewritten[after:].lstrip("\n")


def _lift_nested_utility_blocks(css: str) -> tuple[str, int]:
    """Lift any ``@utility <name> {...}`` blocks nested inside another at-rule."""
    if _UTILITY_MARKER not in css:
        return css, 0
    nested_spans = _find_nested_utility_spans(css)
    if not nested_spans:
        return css, 0
    lifted_text = [css[s:e].strip() for s, e in nested_spans]
    rewritten = _splice_out_spans(css, nested_spans)
    new_css = _inject_after_exepad_layer(rewritten, "\n\n".join(lifted_text))
    return new_css, len(nested_spans)


def _ensure_tailwind_bootstrap(base_css: str) -> tuple[str, bool]:
    """Prepend the Tailwind v4 bootstrap directives when missing."""
    needed: list[str] = []
    if '@import "tailwindcss"' not in base_css:
        needed.append('@import "tailwindcss";')
    if '@import "tw-animate-css"' not in base_css:
        needed.append('@import "tw-animate-css";')
    if "@source " not in base_css:
        needed.append('@source "./components";')
    if not needed:
        return base_css, False
    return "\n".join(needed) + "\n\n" + base_css, True


def _resolve_node_modules() -> str | None:
    """Locate a ``node_modules`` that can resolve ``@import "tw-animate-css"``.

    The standalone ``tailwindcss`` binary resolves bare-package imports relative
    to its ``--cwd``; we symlink the found directory into that cwd. Resolution
    order, preferring a tree that actually contains ``tw-animate-css`` so we
    never link an empty/partial install:

    1. ``$EXEPAD_NODE_MODULES`` — explicit override (set by run.sh / Docker).
    2. ``/app/node_modules`` — the container layout.
    3. Walking up from this module's location to the monorepo root — the
       ``run.sh local`` case, where the agent's CWD is ``apps/agent`` (a Python
       app with no node_modules) but the repo root has the pnpm-installed one.
    4. ``$CWD/node_modules`` — legacy fallback.

    Returns the first candidate that contains ``tw-animate-css``, else the first
    that simply exists, else ``None``.
    """
    candidates: list[str] = []
    env_override = os.environ.get("EXEPAD_NODE_MODULES")
    if env_override:
        candidates.append(env_override)
    candidates.append("/app/node_modules")
    here = os.path.dirname(os.path.abspath(__file__))
    while True:
        candidates.append(os.path.join(here, "node_modules"))
        parent = os.path.dirname(here)
        if parent == here:
            break
        here = parent
    candidates.append(os.path.join(os.getcwd(), "node_modules"))

    first_existing: str | None = None
    seen: set[str] = set()
    for cand in candidates:
        if not cand or cand in seen:
            continue
        seen.add(cand)
        if not os.path.isdir(cand):
            continue
        if first_existing is None:
            first_existing = cand
        if os.path.isdir(os.path.join(cand, "tw-animate-css")):
            return cand
    return first_existing


def _compile_css(
    tsx_dir: str,
    base_css_path: str,
    output_path: str,
) -> tuple[bool, str, list[str]]:
    """Run ``tailwindcss --input ... --output ...``. Returns (success, css, errors)."""
    # (node_modules resolution is delegated to _resolve_node_modules below)
    try:
        cwd = os.path.dirname(tsx_dir)
        nm_link = os.path.join(cwd, "node_modules")
        if not os.path.exists(nm_link):
            node_modules = _resolve_node_modules()
            if node_modules:
                try:
                    os.symlink(node_modules, nm_link)
                except OSError:
                    pass
            else:
                # A missing node_modules is NOT benign: `@import "tw-animate-css"`
                # then fails to resolve, the whole compile fails, and the app
                # ships the raw, unstyled theme.css. In the container this lives
                # at /app/node_modules; in `run.sh local` the agent's CWD is
                # apps/agent (Python, no node_modules), so resolution must walk
                # up to the monorepo root — see _resolve_node_modules().
                logger.warning(
                    "node_modules not found — @import 'tw-animate-css' will not "
                    "resolve and the Tailwind compile will FAIL (app ships "
                    "unstyled). Set EXEPAD_NODE_MODULES or run from a tree whose "
                    "node_modules contains tw-animate-css."
                )

        env = {**os.environ, "BROWSERSLIST_IGNORE_OLD_DATA": "1"}
        result = subprocess.run(
            [
                "tailwindcss",
                "--input",
                base_css_path,
                "--output",
                output_path,
                "--cwd",
                cwd,
                "--minify",
            ],
            capture_output=True,
            text=True,
            timeout=30,
            env=env,
        )
    except subprocess.TimeoutExpired:
        return False, "", ["Tailwind CSS compilation timed out (>30s)"]
    except FileNotFoundError:
        # Fail LOUD: previously this returned success with empty CSS, so a host
        # missing the binary would silently ship the raw, uncompiled theme.css
        # (bare `@import "tailwindcss"`, no utilities) — apps rendered unstyled
        # and the `@import` 404'd in the browser. The container bakes the binary
        # in; `run.sh local` installs it into node_modules/.bin. If it is still
        # missing, that is a real misconfiguration, not a skippable step.
        logger.error(
            "tailwindcss binary not found on PATH — CSS was NOT compiled. The "
            "app would ship raw, unstyled theme.css. Install the standalone "
            "tailwindcss binary (container bakes it in; run.sh local installs it)."
        )
        return (
            False,
            "",
            [
                "tailwindcss binary not found on PATH — CSS was not compiled "
                "(install the standalone tailwindcss binary)."
            ],
        )

    if result.returncode == 0:
        try:
            with open(output_path) as f:
                css = f.read()
            return True, css, []
        except FileNotFoundError:
            return False, "", ["Compiled CSS output file not found"]

    raw_errors = [line.strip() for line in result.stderr.split("\n") if line.strip()]
    errors = [e for e in raw_errors if not any(p in e.lower() for p in _NON_FATAL_PATTERNS)]
    if not errors:
        try:
            with open(output_path) as f:
                css = f.read()
            return True, css, []
        except FileNotFoundError:
            # tailwindcss exited non-zero but only non-fatal/browserslist
            # warnings remained, so ``errors`` is empty — yet the output
            # file is absent. Previously we ``pass``ed and fell through to
            # ``return False, "", []`` (empty errors), which the caller
            # treated oddly (a failure with no diagnostic). Make it fatal
            # and visible instead.
            return (
                False,
                "",
                ["Compiled CSS output file not found after tailwindcss exited non-zero"],
            )
    return False, "", errors


def _write_file(directory: str, filename: str, content: str) -> str:
    """Write ``content`` to ``directory/filename``; return absolute path.

    Containment guard: ``filename`` is (indirectly) LLM-controlled, so assert the
    resolved path stays inside ``directory`` before creating parent dirs / writing
    — otherwise a ``../..`` filename would escape the tempdir.
    """
    path = os.path.join(directory, filename)
    assert_inside_dir(directory, path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    return path
