/**
 * Config types for Exepad Platform
 *
 * Contains: repo config, backend config union, and SecretProps.
 * Frontend types (pages, state, theme, components) live in the runtime package.
 */

import type { ModelProps, HandlerProps } from './backend';

// ─── Repo: custom code repository ───────────────────────────────────────────

/**
 * Repository configuration for all custom code files used by the application.
 *
 * Layout: `repo.frontend.components`, `repo.frontend.styles`, `repo.backend.handlers`
 */
export interface RepoProps {
  /** Frontend code: components and styles. */
  frontend?: {
    /** Custom components keyed by name, referenced in CodeComponentProps. */
    components?: Record<string, RepoComponentProps>;
    /**
     * Babel-shell supporting modules keyed by name. Each entry's `source`
     * is the versioned R2 path; the deploy-time esbuild step stages these
     * next to the entry component and bundles them via cross-file ES
     * `import { X } from "./<Name>"`. Modules are NOT loaded directly by
     * the runtime (no `compiled` path) — they exist only as bundle
     * inputs. Populated by GcsOutputService when an entry component
     * declares `supporting_modules`.
     */
    modules?: Record<string, RepoModuleProps>;
    /** Compiled CSS files injected into the document head (theme, Tailwind output, etc.).
     *  Each entry has `compiled` path resolved via `basePath + /repo/ + compiled`. */
    styles?: Record<string, RepoStyleProps>;
    /** External font stylesheet URLs loaded at page level (Google Fonts, etc.).
     *  @font-face is global — fonts loaded here are available to all components. */
    fonts?: string[];
    /** Path to the Tailwind config file in repo (e.g., 'frontend/code/styles/tailwind.config.js'). */
    tailwindConfig?: string;
  };

  /** Backend code: server-side handlers, tasks, pipelines. */
  backend?: {
    /** Server-side handlers keyed by method name. */
    handlers?: Record<string, CustomMethodProps>;
  };

  /** Seed data (CSV/JSON) — universal descriptor for both static and D1 targets. */
  seed?: Record<string, SeedRepoProps>;

  /** Static assets (images, etc.) managed by the platform. */
  assets?: {
    images?: Record<string, ImageAssetRepoProps>;
  };
}

// ─── Repo sub-types ─────────────────────────────────────────────────────────

/**
 * Defines a custom component code file that can be loaded dynamically via CodeComponentProps.
 */
export interface RepoComponentProps {
  /** Relative path to the TypeScript/TSX source file within the app repo. */
  source: string;
  /** Relative path to the compiled JavaScript file. Generated by the compile step. */
  compiled: string;
  /** Plain-English description of what this component renders, used by the LLM for context. */
  summary?: string;
  /** Content hash of the source file (e.g., 'sha256:3ea3918fb19e35af'). Set by GcsOutputService after upload. */
  source_hash?: string;
  /** Component type discriminator. Used by GcsOutputService to identify code components. */
  type?: 'code_component';
  /**
   * Babel-shell per-module: names of supporting modules this entry
   * component imports from via ES `import { X } from "./Module"`.
   * Each entry corresponds to a `codefocus_module:<Name>.tsx`
   * artifact bundled into this component at deploy time
   * (esbuild --bundle=true). Empty / absent for non-Babel-shell
   * components and for single-file Babel-shell exports.
   */
  supporting_modules?: string[];
  /**
   * Babel-shell deploy-invalidation hash. Computed by the agent as
   * sha256(entry_source_hash + "|" + sorted_module_source_hashes).
   * The entry's `source` path embeds this hash (instead of the bare
   * source content hash) when `supporting_modules` is non-empty —
   * so any module change bumps the path and the backend treats it as
   * a fresh source needing re-bundle. Absent for entries without
   * supporting modules (their `source` path uses the content hash
   * directly, no bundle indirection).
   */
  bundle_hash?: string;
}

/**
 * Babel-shell supporting module — a TSX file imported by an entry
 * component via cross-file ES `import { X } from "./<Name>"`. Bundled
 * into the entry's compiled JS at deploy time (esbuild
 * --bundle=true). Has no `compiled` field of its own because the
 * runtime never fetches modules directly — they exist only as bundle
 * inputs alongside the entry.
 */
export interface RepoModuleProps {
  /** Relative path to the TSX source file in the app repo (versioned). */
  source: string;
  /** Content hash of the source file (e.g., 'sha256:3ea3918fb19e35af'). */
  source_hash?: string;
  /** Module type discriminator. */
  type?: 'code_module';
}

/**
 * Defines a compiled CSS file for Code Focus components, injected into the document head.
 */
export interface RepoStyleProps {
  /** Relative path to the source CSS/config file (e.g., 'frontend/code/styles/theme.css'). */
  source: string;
  /** Relative path to the compiled CSS file (e.g., 'frontend/compiled/styles/theme.css'). */
  compiled: string;
  /** Description for documentation. */
  summary?: string;
}

/**
 * Defines a custom code file for backend handlers, tasks, pipelines, etc.
 */
export interface CustomMethodProps {
  /** Relative path to the TypeScript source file within the app repo (e.g., 'backend/code/handlers/getDashboard.tsx'). */
  source: string;
  /** Relative path to the compiled JavaScript file (e.g., 'backend/compiled/handlers/getDashboard.js'). Generated by the compile step. */
  compiled: string;
  /** Content hash of the source file (e.g., 'sha256:d41d8cd98f00'). Optional for backward compat with pre-deploy configs. */
  source_hash?: string;
  /** Method category for organization and routing. */
  type?: MethodType;
  /** Plain-English description of what this method does, used by the LLM for context. */
  summary?: string;
}

/**
 * Method types for categorization.
 */
export type MethodType =
  | 'handler'   // Backend API handler
  | 'task'      // Background task
  | 'realtime'  // WebSocket handler
  | 'source'    // Custom data source adapter
  | 'pipeline'; // ETL pipeline stage

/**
 * Describes a seed data file (CSV or JSON) stored in the app repo.
 */
export interface SeedRepoProps {
  /** Relative path to seed file in repo/ (e.g., 'repo/seed/contacts_a1b2c3d4e5f6.csv'). */
  source: string;
  /** Content hash of the seed file (e.g., 'sha256:a1b2c3d4e5f6'). */
  source_hash: string;
  /** File format. */
  format: 'csv' | 'json';
  /** Target dataset or model name. */
  model: string;
  /**
   * Seed application strategy.
   *
   * - `'replace'` (default, unchanged behavior): DELETE all rows for the
   *   platform seed owner_id, then INSERT this seed. Idempotent re-deploys
   *   simply re-replace the seed batch.
   * - `'append'`: skip DELETE; rows land under the same platform seed
   *   owner_id as `'replace'` so the logged-in user can still see them.
   *   Prior seed batches (the original `'replace'` seed and any earlier
   *   append batches) are preserved. Used by the DataIngester edit-mode
   *   flow when the user uploads a new spreadsheet that adds to an
   *   existing dataset.
   *
   *   **Re-deploy caveat:** append mode is not idempotent — re-deploying
   *   the same turn re-inserts the rows (duplicates). Treat each
   *   `batch_id` as a single-use deploy token.
   *
   * Absent ⇒ treated as `'replace'`.
   */
  mode?: 'replace' | 'append';
  /**
   * Per-batch identifier for `'append'` mode. Recorded on the seed entry
   * for telemetry/debugging; the seeder does NOT use it to scope DELETE
   * statements (see the re-deploy caveat on `mode`).
   *
   * Required when `mode === 'append'`. Ignored when `mode === 'replace'`.
   */
  batch_id?: string;
}

/**
 * Describes a stock image asset downloaded during app generation.
 * Agent uploads to GCS; backend copies to R2 and sets `url` at deploy time.
 */
export interface ImageAssetRepoProps {
  /** Relative path to image file (e.g., "assets/images/modern-barbershop-interior-pexels-12345.jpg"). */
  source: string;
  /** Content hash of the image file (e.g., "sha256:a1b2c3d4e5f6"). */
  source_hash: string;
  /** MIME type (e.g., "image/jpeg"). */
  content_type: string;
  /** Search keywords used to find this image. */
  keywords: string;
  /** Stock provider name (e.g., "pexels", "pixabay", "unsplash", "openverse"). */
  provider: string;
  /** Provider-specific resource/asset ID. */
  provider_asset_id: string;
  /** GCS source URL (e.g., "gs://exepad-agent-outputs/{uuid}/assets/images/..."). */
  gcs_url?: string;
  /** Resolved serve URL (set by backend after GCS→R2 copy). */
  url?: string;
}

// ─── Backend config ─────────────────────────────────────────────────────────

/**
 * Backend configuration — discriminated union on `mode`.
 * - "static"  → Self-contained JSON artifact with inline datasets
 * - "dynamic" → Deployed app with D1, Workers, etc.
 * - "none"    → Explicitly no backend. Frontend-only app.
 */
export type BackendProps = StaticBackend | DynamicBackend | NoneBackend;

export interface NoneBackend {
  mode: 'none';
}

export interface StaticBackend {
  mode: 'static';
  data: {
    datasets: Record<string, {
      type: 'static';
      records: Record<string, unknown>[];
      schema?: { fields: { name: string; type: string; label?: string }[]; primaryKey?: string };
      generated?: boolean;
      [key: string]: unknown;
    }>;
  };
}

export interface DynamicBackend {
  mode: 'dynamic';
  /** Data models */
  models?: ModelProps[];
  /** Custom handlers */
  handlers?: HandlerProps[];
}

// ─── Secrets ────────────────────────────────────────────────────────────────

/** Declares a secret value (API key, token, etc.) stored securely in KV. */
export interface SecretProps {
  /** The secret name, used as the KV key (e.g., 'STRIPE_API_KEY'). */
  name: string;
  /** Description of what this secret is used for. */
  summary?: string;
  /** If true, deployment fails when this secret is missing. */
  required?: boolean;
}
